### ISSUE TITLE
Wrong slugs for 3D Design and Accounting

### ISSUE THREAD

**Issue by brashrebel** [JacksonCollege/jc-theme-2015#100]
The pathway /pathway/business-computer-technology-2/ (which should have the 2 removed) has the first two degrees using inaccurate slugs. 3D Design shows /accounting/ and Accounting shows /accounting-2/.

**Comment by banksashleym** [comment]
These have been fixed - and I will go through the other pathways/programs and make sure all the slugs are correct.
