### ISSUE TITLE
Interactive campus map

### ISSUE THREAD

**Issue by brashrebel** [JacksonCollege/jc-theme-2015#102]
Many organizations with large campuses like colleges, theme parks, zoos, etc. have found it useful to present users with interactive, functional maps of their facilities. Currently there are a number of static image aerial maps on the JC website. I propose that we look into creating more compelling, visually appealing, intuitive and useful maps with which visitors will be able to explore the campus in greater detail, obtain more accurate information in less time, and reduce content maintenance issues by leveraging existing information.

This would be a significant project of its own so I'm just starting the conversation here.

**Comment by banksashleym** [comment]
We hope to address this in a redesign - closing this one as well.
