### ISSUE TITLE
Landing Grid ability to change link text

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#105]
Could i have the ability to control what the link text is in the landing grid boxes? I have used those boxes throughout the site and love them. There are some instances where I would like to change the link text to something other than "Learn More"

Thanks!

**Comment by brashrebel** [comment]
Do you have an urgent need for this functionality or could we milestone this for a post launch enhancement?

**Comment by banksashleym** [comment]
No, this isn't urgent - we can wait until after launch.
