### ISSUE TITLE
Shortcode UI

### ISSUE THREAD

**Issue by brashrebel** [JacksonCollege/jc-theme-2015#107]
I believe the content management would be made much simpler for anyone working on this site if, instead of needing to know which shortcodes exist and how to use them and referring to (currently non-existent) documentation, we made a button in the editor which allowed content editors to select from available shortcodes.

I would recommend closing this issue once a simple version exists and opening separate issues for each unique shortcode which exists.

**Comment by banksashleym** [comment]
Closing this as well as. We are looking to do a refresh of the site soon and can revisit at that time if something like this is needed.
