### ISSUE TITLE
Not much going on in spotlight sidebar

### ISSUE THREAD

**Issue by brashrebel** [JacksonCollege/jc-theme-2015#122]
When viewing a spotlight, the only thing in the left sidebar is the archive link for the year. First off, that's not a lot of stuff. Maybe those 3 buttons should be there? Secondly, a _year_ archive strikes me as not super helpful unless we're going to include other years and even then it isn't ideal. I think maybe by month or just simply by title, the 5 most recent would be better. Maybe also a "Recent News" type section as well.

**Comment by banksashleym** [comment]
I'm going to close this as well as it's not really a priority at this time.
