### ISSUE TITLE
Enhanced FAQs

### ISSUE THREAD

**Issue by brashrebel** [JacksonCollege/jc-theme-2015#126]
[Over here](http://www.jccmi.edu/admissions/course-placement/) there are FAQs which I believe could be enhanced. Common ways to present FAQs include listing the questions at the top of the section as links which take you to the answer further down the page OR making all the question headings clickable so the answer appears below the question when clicked on. We call those accordions. I'm not sure whether there are other sections of the site which could benefit from this kind of UI but at least here it would make the content easier to consume.

**Comment by banksashleym** [comment]
Yes, there are multiple pages where the FAQ are presented this way...I believe you built in some functionality with regard to FAQ's and that is on my to-do list as well, to update all of the FAQ pages to have the content be presented in a more dynamic way.
