### ISSUE TITLE
New placement for TCS2 logo on home page

### ISSUE THREAD

**Issue by brashrebel** [JacksonCollege/jc-theme-2015#146]
As of last week's meeting, this was not exactly decided but it is being discussed and investigated. The goal is to find the optimal placement for the TCS2 logo. A lot of different ideas were discussed at the meeting and at this point we are seeking further input from JC staff regarding the importance of this item and some ideas for placement. Once we have some more guidance we can possibly put together some conceptual prototypes to demonstrate a few different ideas.

**Comment by banksashleym** [comment]
We will have an internal discussion about this and get back to you.
Thanks!
