### ISSUE TITLE
Adjust programs of study grid for more items per row

### ISSUE THREAD

**Issue by brashrebel** [JacksonCollege/jc-theme-2015#147]
[This page](https://www.jccmi.edu/academics/programs-of-study/) should present six items in a row on wide screens. For what it's worth, I really like how it looks now.
![screenshot 2016-06-21 09 58 14](https://cloud.githubusercontent.com/assets/4993131/16231999/baa6bb82-3796-11e6-8c9d-0a3b51cfd8a4.png)

**Comment by banksashleym** [comment]
We can put this on the back burner for now as well. Now that I look at it it does seem nice and colorful. And I'm worried that if we make them any smaller the text will become confusing.

Thanks!
