### ISSUE TITLE
Faceted site search

### ISSUE THREAD

**Issue by brashrebel** [JacksonCollege/jc-theme-2015#150]
The JC site currently has the following types of content:
- News
- Media
- Pages
- Alerts
- FAQs
- Staff
- Locations
- Profiles
- Spotlights
- Jobs For Jets
- Events
- Pathways
- Programs
- Degrees
- Courses

Here's what we need to do:
## Step 1

Define which of the above content types should be included in search results.
## Step 2

Mock up a new search results page. We can do this unless Ashley wants to. If so, let me know and we'll discuss ideas first.
## Step 3

Once a design has been agreed upon, we will modify the search results page to look like the mock and make it so results can easily be filtered by selecting from the various types of content.

**Comment by banksashleym** [comment]
I think we should include news, pages, events, programs, profiles and spotlights. I can work on a mockup for the new search results page.

Thanks!

**Comment by brashrebel** [comment]
Ok, great. Before you get to far I'll share some thoughts to inspire you.

First off, I've always appreciated the search feature inside of Salesforce which very clearly sorts the results by type and shows you how many of each type were found. Also you can select to only search for results of a given type.
![search_results](https://cloud.githubusercontent.com/assets/4993131/16280539/06ae2dec-388e-11e6-8772-8e9a3c1dcf3d.png)

Another good UI that I find intuitive and useful is the one Google Calendar uses for showing the various calendars shared with your account. You can color code them all and, with a click, show and hide entries from that calendar in your current view (also this could be similar to what we implement for #155 :
<img width="301" alt="screenshot 2016-06-22 15 29 32" src="https://cloud.githubusercontent.com/assets/4993131/16280587/52a34872-388e-11e6-9e13-1a19c54bcb16.png">

You can also draw inspiration (at least from the information and UX) from the JDL catalog search. Notice how each entry has a little icon next to the Format label indicating what type of result it is. Also the left sidebar has a group of links showing the types and numbers of those types returned:
<img width="1016" alt="screenshot 2016-06-22 16 14 08" src="https://cloud.githubusercontent.com/assets/4993131/16281906/6c990392-3894-11e6-8749-05294e7a4295.png">

Here are some other questions to reflect on:

- Should the results be one, single stream or broken into sections by type (like in the Salesforce example)?
- Especially if they are in a single stream, how will different types be visually distinguished? You could use color, text, layout or icons to make it clear at a glance which results correspond with which type of content.
- Are you certain about the search results only including those content types? What if I searched for "Dan Phelan" or "Del Belcher". Wouldn't their staff profiles be the best result? And what if I searched for "Human Services"? Shouldn't the pathway be returned? It seems like the academic content types may be searched for and should be found. There's honestly only a couple content types that seem like poor candidates for search. Mostly just Media and Alerts. In theory, if someone is able to look for and find something on the site, they should also be able to search for it.
- What is the easiest way for users to select the types they wish to see? Should they only be able to see all types or one type? Or should they be able to cherry pick multiple types to show? If it is the former than they should just be links or a radio group of some kind. If it is the latter than some type of checkbox group or buttons that highlight when selected.
- Should the number of found results be listed next to the type selectors?
- Should all types be listed all the time or only those that have results? Presumably, if we listed all types all the time, we'd show (0) for zero results next to the content types that returned no entries (like the Salesforce example).
- Also, consider what is shown when no results are found. Currently that view is not pretty, friendly or helpful in any way. Just a bleak screen of sadness:
<img width="285" alt="screenshot 2016-06-22 16 03 34" src="https://cloud.githubusercontent.com/assets/4993131/16281571/0269c5d4-3893-11e6-9354-bc7d1c489089.png">
Maybe spruce that page up with at _least_ some more helpful text?

Let me know if you want to talk about ideas.

**Comment by banksashleym** [comment]
Thanks so much for providing these examples! I think keeping it simple and clean, yet providing the end user with the result they are looking for is the end goal. That said, I really like how the Salesforce search categorizes the results. I think this would really help define what people are looking for. I also agree with your statement about searching for people and degrees, but I think we can eliminate the pathway category, since this would show up in pages. 

Could we include **news, pages, staff, events, programs, profiles and spotlights, programs and degrees**? And have the results show up like Salesforce, where they are put into categories? I can still create a mockup of how we would like them presented. I will work on that today.

Thanks so much for the inspiration!

**Comment by brashrebel** [comment]
Thank you @banksashleym ! A mockup would be perfect and I agree with your plan. Perfect.

**Comment by banksashleym** [comment]
Good deal! This is going to be great :)

**Comment by joelworsham** [comment]
@banksashleym Should I await a mockup for this or should I go for it?

**Comment by banksashleym** [comment]
So sorry about the delay in getting this to you. Here is kind of what I was thinking. Listing the categories along the side (I deleted "degrees" since they will be able to find all degree information through "programs") and then being able to toggle on/off the categories a user would like to show and hide. This is just a guide, if you have any additional things that would spruce this page up we are definitely open to suggestions! Also, for the sub text (for instance "About TRiO") the sub text is pulling in the header and then the paragraph, so it reads "About Trio Trio is a 100% etc.." Is there a way to just pull in the paragraph and not the header, so it would read "Trio is a 100% etc..." There are a lot of pages that the description doesn't make sense because of this.

![site seach mockup](https://cloud.githubusercontent.com/assets/15264315/17750102/9ad69b40-648e-11e6-8bfe-b9889ed336cf.jpg)

**Comment by banksashleym** [comment]
This is absolutely perfect, I wouldn't change a thing! I will go through the pages and start building out keywords using custom fields.

Thanks!

**Comment by banksashleym** [comment]
Sorry, I am thinking about one thing - Could we re-order the items (both in the left side navigation area and in the area where the results show) and show the results in this order?

- Programs
- Pages
- Events
- News
- Profiles
- Staff
- (eliminate spotlight)

Thanks!

**Comment by banksashleym** [comment]
Could we also include an option for staff that pulls the info from the staff plugin?

**Comment by banksashleym** [comment]
Sorry, also could we have the text from the program drop below the image on mobile?
![mobile](https://cloud.githubusercontent.com/assets/15264315/18351893/09855e38-75aa-11e6-8f81-b1f142ca1106.jpg)

**Comment by joelworsham** [comment]
All set

**Comment by banksashleym** [comment]
Thanks, this is great! The only thing I'm not seeing is the staff option in the l left nav like mentioned above? It would be a nice feature to have someone search for a staff member of the college and be able to quickly get their contact info in the search results.

Thanks!

**Comment by banksashleym** [comment]
No worries, we can leave them private and not include them in the search. Thanks for looking into this!

**Comment by brashrebel** [comment]
I think we should open an enhancement issue for this. It would be nice to make the post type public, style the single entries and incorporate them into the search. There could be lots of instances in which we want to be able to link to staff directly and it would add a lot of depth to the site.

**Comment by joelworsham** [comment]
I agree with @kyle

**Comment by banksashleym** [comment]
Issue after launch:
On the search page, the search is pulling all content types, including courses, degrees and pathways but it was set up on the staging to only pull Programs, Pages, Events, News, and Profiles (and not courses, degrees, pathways or spotlights). Thanks!

**Comment by joelworsham** [comment]
Ah yes. It seems that Relevanssi had not yet been setup to pull specific content types. I've just set it to only pull Programs, Pages, Events, News, and Profiles.

**Comment by BigActual** [comment]
Can this be closed?

**Comment by joelworsham** [comment]
I believe so, yes.
