### ISSUE TITLE
Create archive for profiles

### ISSUE THREAD

**Issue by brashrebel** [JacksonCollege/jc-theme-2015#152]
At this time, the profiles content type has no archive. Trying to navigate to it [returns a 404](https://www.jccmi.edu/profiles/). We should make a profiles archive. I don't know what it should look like. We have lots of archives on the site so I'd advocate for using an existing design. 

We also need to work it into the breadcrumbs and the menu somewhere (maybe).

**Comment by d4mation** [comment]
Tried to cross-reference via commit but it didn't seem to work.

This change also requires the changes from [this branch](https://github.com/JacksonCollege/Student-Profiles/tree/Primary-Theme/issue/152/profiles-archive) for the Profiles CPT plugin (and Permalinks need to be flushed).

**Comment by banksashleym** [comment]
Same as issue #153 :) would like to be able to incorporate "recent posts" widget as well as "archive" widget so that it mirrors the news section.

Thanks!

**Comment by d4mation** [comment]
Technically the Profiles Archive uses the same templates at the News Archive, so with this Branch it should already show the same Widgets that are in the News Section.

When you switch to this Branch (And the corresponding Branch of the Profiles CPT plugin) is it showing you something different?

![image](https://cloud.githubusercontent.com/assets/7770631/18180783/5a638900-7056-11e6-951c-e6ccb67ef60c.png)

**Comment by banksashleym** [comment]
See issue #154, I think that covers this issue as well!

**Comment by d4mation** [comment]
Yep! I'll have to fix this up so that it will use the Profiles Widget Area as well. Then having a fixed Widget to show the proper Archives should handle it 👍

**Comment by d4mation** [comment]
Just pushed a change to this branch to replace the "News" Widget Area on Profiles Archive Pages with the "Profiles" Widget Area.

Like I mentioned in #154, the new Archives Widget isn't on this Branch but it will be available once everything comes together at the end.

**Comment by banksashleym** [comment]
Sounds good, this looks good, thanks!
