### ISSUE TITLE
Better spotlights archive page

### ISSUE THREAD

**Issue by brashrebel** [JacksonCollege/jc-theme-2015#153]
The spotlights content type does have an archive now. [It's just lame](https://www.jccmi.edu/jc-spotlight/). We should spruce it up. Also, the results are not showing great excerpts.

**Comment by banksashleym** [comment]
Yes, perfect.

**Comment by banksashleym** [comment]
This ties in with #154. I would love for the spotlights left side to be style like the news section (I was able to put widgets there) where I could apply a list of recent posts as well as a drop down list for archives.

**Comment by banksashleym** [comment]
I really like how this archive page looks where it pulls the spotlight image and text! (see issue #154 for sidebar functionality)...Could we make these images into a grid, maybe with 3 across? The images seem just a little big :)

Thanks!

**Comment by joelworsham** [comment]
Check that out, let me know if you like it.

**Comment by banksashleym** [comment]
I like this! It does seem to cut out a lot of the picture though? I'm ok with some of the content being cut out, but it seems like the pictures are very magnified here?

**Comment by joelworsham** [comment]
Sure thing. I've modified it so that the background zooms out as much as possible.

**Comment by banksashleym** [comment]
Looks good, thank you!
