### ISSUE TITLE
Allow events calendar to be filtered by category

### ISSUE THREAD

**Issue by brashrebel** [JacksonCollege/jc-theme-2015#155]
In order to improve the experience for users who may be only interested in specific types of events *and* to allow departments to be able to link directly to a calendar which lists only their events, we need to make further use of event categories. At this time, I do not believe we need another taxonomy but that is open for discussion. Event categories exists already and is barely used.

The plan is to make categories for all the different categories of events (which Ashley can already do) and then make it so:

1. When viewing the events calendar, categories can be selected which will narrow the results to only include events in those categories.
2. Implement a permalink structure which will allow for linking directly to a filtered results view for a category. Something like `/events/athletics` for example may show only athletic events.

**Comment by banksashleym** [comment]
Perfect!

**Comment by banksashleym** [comment]
I have switched the theme to #155 and create a new category "Student Services" and attached that category to 2 events I believe. Could you explain how I would then see just the Student Services events or what that permalink structure would look like? I tried /events/student-services and got a 404. 

Thanks!

**Comment by joelworsham** [comment]
Aha yes. So, sometimes permalinks get wonkey and need to be "flushed'. To do so, you simply have to visit the Settings -> Permalinks page. You don't even have to save anything, you just visit the page in your browser. https://jacksoncollege.staging.wpengine.com/wp-admin/options-permalink.php

So, in this case, I had to switch the theme branch to this issue and then flush the permalinks, and then the event categories worked.

If you ever notice that links don't seem to be working right, try flushing the permalinks.

As for the URL, it will look like this `https://jacksoncollege.staging.wpengine.com/event-category/student-services/`

**Comment by banksashleym** [comment]
Perfect, thank you!

**Comment by banksashleym** [comment]
This looks great!

**Comment by banksashleym** [comment]
Marilynn just brought up a good point with the events section. Could we have the option to control what events show up on the home page? Like maybe a checkbox when we create the event to allow it to show up in that events listing on the homepage? We have a few student groups that meet three times a week, and we would like to include those meetings in the calendar style events portion, but those events would take up all of the spots on the homepage. Thanks!

**Comment by joelworsham** [comment]
Sure thing

**Comment by joelworsham** [comment]
All set. I've added a dropdown when editing an event to hide it from the home page listing. If you set that to "hide", it simply will not show on the home page.

I've got the theme branch switched already for testing.

**Comment by banksashleym** [comment]
Looks great!
