### ISSUE TITLE
Improve handling of long alert messages

### ISSUE THREAD

**Issue by brashrebel** [JacksonCollege/jc-theme-2015#157]
In some instances, alerts contain more text than was originally anticipated and the result isn't pretty. We have a few options for how to handle this.
- Alerts can be presented in different ways (popups, inline, etc.)
- Messages can be truncated with a "Read more" link added when they get too long
- The alerts container can be adjusted to better fit the window

If someone could shed more light on this, possibly with screenshots or something that would be helpful. Also, we can even consider modifying something on the backend so the author could be made aware of the limitations that they are working with.

OR perhaps we could incorporate alert authoring in the customizer so a live preview could be visible. That would be really cool.

**Comment by banksashleym** [comment]
This really wasn't an issue to me :) I think we can get by with doing a pop-up or the "read more" link if we have longer messages. If we have any additional issues with future messages maybe this is something we can look into, but for now let's put this on the back burner.
