### ISSUE TITLE
Site Section Manager bug

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#161]
I have a user that is assigned as a site section manager, but she is only able to see pages that have been published - she is not able to see any drafts in her section. She created a page and saved the page as a draft, and when she logged back in the page was gone. I was able to see the draft page on my end, and when I published the page she was able to see it in her list, but when I unpublished and made it a draft again it disappeared.

**Comment by banksashleym** [comment]
I referenced this in issue #148 ...now that there is only a "submit for review" button, the site section managers don't have the availability to save as a draft anymore...could we still incorporate saving as a draft so that they can save the page and come back to it before submitting to me their final changes?

**Comment by joelworsham** [comment]
Ahhh good point. Yes this can be added back in.

**Comment by joelworsham** [comment]
All set. Draft button is available for site section managers

**Comment by banksashleym** [comment]
This is perfect, thank you!
