### ISSUE TITLE
Enable single staff profile pages

### ISSUE THREAD

**Issue by brashrebel** [JacksonCollege/jc-theme-2015#163]
As discussed at the end of #150, currently staff profiles are not accessible individually. So it is not possible to navigate to jccmi.edu/staff/ashley-banks or to use that post type in features like faceted search. It would be a nice enhancement to the site to enable single versions of this post type.

The benefits would include:
- Allow individual staff profiles to be linked to directly throughout the site
- Give staff a place to link to and show off their staff profile
- Include staff in search facets
- Increase usability of staff listings throughout site
- Open up opportunities to add more useful information to staff profiles without having to fit it all inside listing entries
- Add more depth to the site's overall content

The requirements would be:
- Make the post type public
- Create a styled layout concept for the individual entries
- Incorporate that new layout template into the theme
- Add the post type to the search facets
- Possibly modify staff lists to include links to the individual entries

**Comment by banksashleym** [comment]
Yes, this sounds wonderful :)
