### ISSUE TITLE
Mobile phone scrolling is now jagged and not fluid like before

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#164]
Issue after launch of 1.2 updates:
This isn't a huge deal, but just thought I would log it. When I view the site on my iphone the page now scrolls differently? It’s almost jagged scrolling and not fluid like how it used to be? This only applies to the iphone I believe, I checked it on Del’s Samsung phone and it works fine on his. Let me know if you need me to explain it more!

**Comment by d4mation** [comment]
I just checked on my wife's iPhone and the scrolling on the home page seems fluid. Is there a specific page that is giving you trouble?

I think that you may have some of the old CSS and JavaScript files cached on your iPhone which could be causing the stuttering. If you go to Settings->Safari->Advanced->Website Data->Edit and then clear the stored data for `jccmi.edu` it should force your iPhone to fetch the latest versions of the files.

You can also hit "Remove All Website Data" if you are unable to find it within the list.

**Comment by banksashleym** [comment]
This is weird, i deleted all of my website data and it still seems to scroll hard? Before the updates, when I would scroll down and move my finger from bottom to top and let go, the page would still scroll down, but now when I lift my finger up the page immediately stops. This isn't a big deal, and I'm sure no one else will notice, just thought that it was a little weird! I just tested it on my co-workers iphone and it is doing it on hers too, but just on the JC website on all pages.

**Comment by d4mation** [comment]
Ah, now I know what you're talking about. I'll have to look into this later this afternoon once my wife is back from grad school since that "momentum" when you scroll and lift your finger works normally on my Nexus 6P. I'll check to see if I can reproduce it on my wife's iPhone.

**Comment by d4mation** [comment]
Just got a hold of an iPhone to test and I believe this is good to go!

When you get the chance, could you check out http://jacksoncollege.staging.wpengine.com/ to confirm for me? I've already switched Staging to the appropriate branch while testing on my own.

**Comment by d4mation** [comment]
Changes are Live!
