### ISSUE TITLE
Change Open Sans to medium default weight

### ISSUE THREAD

**Issue by joelworsham** [JacksonCollege/jc-theme-2015#166]
Right now the Open Sans Google Font loader is using a thin weight for default texts. We need to change this default weight to medium (regular, normal), and don't load in the thin weight at all.

**Comment by banksashleym** [comment]
Hi Joel, just checking in on this issue? I have still been getting quite a few complaints saying that students are having a hard time reading the text in Chrome. Thanks for any info you can provide!

**Comment by joelworsham** [comment]
Sorry about letting this slide to the wayside! I'll take a look into this tomorrow morning.

**Comment by banksashleym** [comment]
It's ok! I hate to put things on your plate when they haven't been scheduled so I completely understand. I imagine you must be very busy - I appreciate your help!

**Comment by joelworsham** [comment]
I've updated this on the staging site. Let me know what you think, and if we're good to go, I'll update it on the live site.

**Comment by banksashleym** [comment]
Looks fantastic, thank you!!
