### ISSUE TITLE
Run PHP7 compatibility checker

### ISSUE THREAD

**Issue by brashrebel** [JacksonCollege/jc-theme-2015#167]
WP Engine will be offering PHP7 pretty soon. Right now you can opt in for possible early access (if you want it) by running the [PHP7 compatibility checker](https://wpengine.com/blog/php-7-compatibility-checker-plugin/) on the site.

**Comment by banksashleym** [comment]
Thanks! I ran the compatibility checker. It came up with a few errors. How would you like me to send the information to you? Do you want to log in to the dashboard and see the results? or here is the text report.

[report.txt](https://github.com/JacksonCollege/jc-theme-2015/files/597521/report.txt)

Thanks for letting me know about this!

**Comment by brashrebel** [comment]
Thanks @banksashleym! Great work. Just read through the report. Looks like we're close but not completely ready for PHP7. This next version is pretty exciting and I do recommend moving to it as soon as possible. It is more secure, stable and much, much faster. That said, there's no deadline so I'd simply recommend adding this as a to-do for the next time we do some work on the site.

All that will be required is updating some of the third party plugins, phasing out a couple that are no longer needed and making some modifications to a couple that we created. Not very intense at all.

**Comment by BigActual** [comment]
@banksashleym - We need to take you up to PHP 7. I'll reopen this issue until it's been addressed. It's a bit of a process and we'll need to talk it through.

**Comment by banksashleym** [comment]
Sounds good, thanks!
