### ISSUE TITLE
New degrees not pulling site section properties

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#175]
Hello, we just recently got a new degree. When I added the new degree and added it to the Culinary Program, the page doesn't pull in the culinary header/side navigation like the other degrees do. I've tried adding other degrees in other programs as well and they are doing the same thing. The degree is the Culinary Arts and Hospitality Management - Bachelor of Science degree and it is added to the [Culinary Program](https://www.jccmi.edu/program/culinary-arts/). Right now I have the pdf override feature on the page, so that when I click on the degree link it goes to our guidesheet, but when I remove the pdf the page doesn't have the header or left side nave of culinary. If you could look at this when you get a chance I would surely appreciate it!

Thanks!
Ashley

**Comment by joelworsham** [comment]
Hey Ashley. The reason for this is that you forgot to add the new degree to the "Site Section". So technically, there was no association between the degree and the Culinary site section. You can see I've added it here:

![](http://d.pr/i/1rO4aT+)

I have **not yet** disabled the PDF override. I'll let you take a look and then you can disable it if all looks well.

**Comment by banksashleym** [comment]
oh wow, I feel really dumb. You can tell it's been a while since I've added a degree. Sorry about that, thanks so much for looking into this!

**Comment by joelworsham** [comment]
Ha, no worries! It is, admittedly, a bit of a complex system with many moving parts. Easy to lose track of one of them!

**Comment by banksashleym** [comment]
I think we can close this one!
