### ISSUE TITLE
Adding "weekly" option to event does not work

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#177]
We have many of the same types of meetings that occur on a weekly basis. This functionality no longer works? I created a "test event" to run from Monday, 2/20/17 until Monday 8/21/17 and clicked on the "weekly" option in the repeat drop down. When I view the calendar the test event shows up every Tuesday, but in the March calendar they show up every Wednesday, in the April calendar they show up every Saturday, and in the May calendar they are back to every Tuesday. It seems that with every month the day changes.

**Comment by joelworsham** [comment]
All set!

**Comment by banksashleym** [comment]
Awesome, thank you!!
