### ISSUE TITLE
Enter license key for WP Slick Slider so we can update the plugin

### ISSUE THREAD

**Issue by joelworsham** [JacksonCollege/jc-theme-2015#178]
Here's the page to do so: https://www.jccmi.edu/wp-admin/plugins.php?page=slickspro-license

**Comment by banksashleym** [comment]
Hi Joel,
I'm actually in the process of removing all of this information and migrating it to a different plugin "Master Slider". This plugin's license has expired and I wasn't too wild about it anyways. i will be deleting it probably early next week after I have moved the info over.

Thanks!

**Comment by joelworsham** [comment]
Thanks for the info, Ashley!
