### ISSUE TITLE
Add preview button for developers

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#183]
Is there a way for our site section manages to have a preview button when making changes to a page? Currently they only have the option to "save draft" or "submit for review." It would be nice for them to preview their changes in a browser before sending them to me.

Thanks!
![capture](https://user-images.githubusercontent.com/15264315/29073232-e793cdde-7c18-11e7-9b49-d4ce59000a31.JPG)

**Comment by joelworsham** [comment]
I see this issue now was already here. I'll close this in lieu of the new one.
