### ISSUE TITLE
Allow image to float right for news item

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#184]
Is it possible for the image in the news items to float to the right and have the text wrap around it instead of sit at the top of the text? Either that or have the option to set the featured image of a news item on the home page, and then be able to not use that featured image in the actual post? Let me know your thoughts on this. For instance, if we had the large main news feature image from the following post float to the right with the text floating around it, there would be the large image and a small column of text to the right since the picture is so large. Or maybe for the large feature set a specific size that it would scale down to when it is in the post floated to the left?

There just seems like a lot of wasted space to the right of an image in the news items :)

Thanks!

**Comment by joelworsham** [comment]
I've added the ability to hide the featured image from News posts. This way, if you would like to add a custom image with custom text-wrapping, you can simply add the image into the content manually.

Let me know if this works for you. Thanks!

**Comment by joelworsham** [comment]
I didn't mention _how_ to hide the image! Go to the Edit screen for the News item you want to hide the image for, then scroll down to the Featured Image area. Right above it you will see a checkbox to hide the image.
