### ISSUE TITLE
Spotlight images float right instead of in own column

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#185]
Could we have the image in the spotlights float to the right with the text flowing around it instead of the image being in it's own column? 

Thanks!

**Comment by joelworsham** [comment]
I've set it so it floats to the right *only on large screens*. It was causing the text to be very unreadable on medium-small screens. See example:

## Float on all screens:
![](http://d.pr/i/hE2YTC+)

## Float **only** on large screens:
![](http://d.pr/i/my7TpE+)
