### ISSUE TITLE
Info from various dynamic plugins goes across footer when expanded

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#186]
Hello! There are a few plugins that we installed (gravity forms, FAQ, WP data tables) that have content that can be expanded, but when that content is expanded the page doesn't expand with it, the content just goes over the footer. See example here with the FAQ list [here](https://www.jccmi.edu/pei/frequently-asked-questions/).

Is there a way you can make is so that outside plugin content extends the page rather than go in front of the footer?

Thanks!

**Comment by joelworsham** [comment]
Yes! I know exactly why this happens. I will fix it next week.

**Comment by joelworsham** [comment]
The issue here is the 3rd-party plugin you're using for FAQ doesn't account for something in the theme that sets content height.

Can I ask why you're using this 3rd-party plugin instead of the JC FAQ plugin?

**Comment by banksashleym** [comment]
Oh, gotcha. Yes, actually when the site first launched a department had to get some FAQ's up and I don't think we ever discussed what the shortcode was to put the FAQ's on the page so I downloaded that one in a pinch :) I will start to transition everything over to the FAQ plugin Real Big Marketing created and get that third party one out of there. Could you tell me the shortcode for that plugin?

Thanks!

**Comment by banksashleym** [comment]
And actually, is there a way to write out the FAQ's on the actual page instead of writing them in the plugin? Or give maybe give access to the FAQ's plugin to the site section managers? I have a lot of users who want to make changes to their FAQ's but they don't have access since the content is housed in the plugin. Thanks for any input!

**Comment by banksashleym** [comment]
Awesome, thanks!

Yes, I would love for a developer to be able to have access to the plugin so they can edit/add to their topic.

Before we migrate these over, is there a way we could style the new FAQ so that it matches the styling of the Responsive FAQ plugin? Thanks!

**Comment by joelworsham** [comment]
Sure thing. I'm going to open a couple corresponding issues and close this one out.
