### ISSUE TITLE
WP Data tables no longer visible on site

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#187]
Hello! Just wondering if the WP Data Tables plugin was recently updated? Most of the tables are gone on the site and the ones that are there are showing up very weird: Policy Site (http://www.jccmi.edu/policies/). If this could be fixed asap that would be great. Yesterday was the first day of classes and the course schedule (which uses this plugin) has been very active lately.

Thanks!
Ashley

**Comment by joelworsham** [comment]
I've been looking into this and I cannot figure it out. You will need to contact the plugin support team.

**Comment by banksashleym** [comment]
Thanks Joel,
Is there a way to roll back to the previous version before the plugin until we figure that out?

**Comment by banksashleym** [comment]
I checked out their support forum and someone was having the same problem. It was suggested deactivating the plugin and then re-activating. It seemed to do the trick. weird :)

**Comment by joelworsham** [comment]
Oh, great! Glad to see it fixed!
