### ISSUE TITLE
FAQ Topics assignable to site editors

### ISSUE THREAD

**Issue by joelworsham** [JacksonCollege/jc-theme-2015#190]

**Comment by banksashleym** [comment]
Hi Joel,
I just had a chance to assign a developer to an FAQ topic. Everything worked great except for when she submitted it for review it never had a topic assigned to it so when I clicked on "accept" it never showed up on the page - I had to go back into that specific FAQ and assign it a topic. Would there be a way that a developer would be able to see the topic list and then just be able to select their topic?

Thanks!
Ashley

**Comment by joelworsham** [comment]
Sure, I can set it up so that when someone creates one, it auto-adds to their category if they have 1 and they can choose if they have more than 1. You can follow the new issue here: #216

**Comment by banksashleym** [comment]
That would be perfect!!
