### ISSUE TITLE
Tabs shortcode mobile size

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#193]
Hello, is there a way for the tabs shortcode to be configured into accordion drop downs when viewed on tablets/phones? Whenever I view a page with tabs on my phone it looks a little confusing. See the [Academic Deans](https://www.jccmi.edu/academic-deans/adjunct-resources/) pages. When I condense this down and want to view the resources tab, all of the other tabs populate below it and the actual tabbed content doesn't show up until after all of the tabbed buttons. Would it be possible if they convert to look like the FAQ tabs when viewed on tablet/phone so when you click on it it will expand with the info?

Thanks!

**Comment by joelworsham** [comment]
That's a great thought. I'll look into it!

**Comment by joelworsham** [comment]
After looking into a solution for this, I discovered that the newest version of Foundation (we're on version 5; 6 is the latest) this is natively supported.

I believe upgrading to Foundation 6 needs to happen ASAP anyways. It brings a lot of features, bug fixes, and overall improvements.

Anyways, rather than attempting to hack my way through getting this issue fixed, I'd prefer to put it on the back-burner and use the new feature in Foundation 6.

**Comment by banksashleym** [comment]
This sounds good to me!

**Comment by joelworsham** [comment]
I'm going to close this issue in favor of a new issue regarding upgrading Foundation. I'll talk with Steve on more specifics of how we can tackle this!

Follow in issue #202

**Comment by banksashleym** [comment]
Hello, could we look into this again now that we have upgraded to Foundation 6? This would be very convenient to be able to take the tabs and convert to an accordion style on mobile, especially with a page like the [Tutoring Center](https://www.jccmi.edu/center-for-student-success/tutoring-center/). When I view this page on my phone the list of tabs takes up a lot of space and the information for each tab populates below that. Thanks for looking into this!

**Comment by d4mation** [comment]
I've just pushed this change to the Staging site 👍 

You can see it in action here: http://jacksoncollege.staging.wpengine.com/academic-deans/adjunct-resources/

**Comment by banksashleym** [comment]
This is amazing!! Love it - it's exactly how I pictured it. Could we force this view to anything less that a standard desktop size? I'm thinking even tablets as well. It cleans up the content so nicely!

**Comment by d4mation** [comment]
Just adjusted it to happen for Tablets as well 👍

**Comment by banksashleym** [comment]
Wonderful!! I love it!

**Comment by d4mation** [comment]
This change is now on Live 👍
