### ISSUE TITLE
Install Gravity Forms encryption plugin

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#194]
Me again! Just wanted to ask a question about the security of the gravity forms? We had a session on cyber security yesterday and they touched on what to do if there was a breach in data. I realized that we have a Direct Loan form on the site that is very active and that students have to give their SSN numbers. 

I'm assuming that gravity forms itself doesn't have any security associated with it - is the SSL certificate we have implemented on our site enough to protect this kind of sensitive data? Should I be doing anything else to ensure that any data coming in from those forms will be secure?

Thanks!!

**Comment by joelworsham** [comment]
That's a great question. The SSL certificate absolutely protects input data from being intercepted. It encrypts all incoming and outgoing data.

The issue here is that once the data makes it into the website, it is stored *not* encrypted. If, somehow, your website was compromised and your data leaked, all of that information would become available.

It is critical that you take as many steps towards securing your website *as a whole* to prevent such a leak. Methods to aid this can include (some of which you're already doing):

- SSL EVERYWHERE
- WordPress extra security plugins
- Routine security audits from professionals and/or automated services
- Update *everything* frequently
- Do your own audit routinely on plugins you have installed. The more plugins, the more opportunity for error. Double check they all are from reliable developers.
- Don't *ever* email something you wouldn't be okay with anyone else seeing. Emails are *not* secure. Make sure Gravity Forms is not emailing any sensitive information in its notifications.

We could also look into extending Gravity Forms manually to encrypt certain fields on entry to the database.

There are also some (sadly, few) plugins out there to help encryption, like this: https://codecanyon.net/item/gravity-forms-encrypted-fields/18564931

**Comment by banksashleym** [comment]
Wow, thank you so much! I hate the thought of names/emails/ssn being readable in the admin portion of the site. I am going to see if Dotty will buy this plugin. Thanks for the great info!

**Comment by joelworsham** [comment]
No problem! Feel free to re-open this issue with more questions, should you ever have them.

**Comment by banksashleym** [comment]
Hi Joel,
We ended up purchasing the plugin you suggested above to encrypt or data. I read the readme.txt file and it seems like it's a little more complicated than just uploading/activating the plugin. Could we add this to our list of weekly issues? I have included the zipped file I downloaded from codecanyon.

Let me know if you have any questions!
[codecanyon-18564931-gravity-forms-encrypted-fields.zip](https://github.com/JacksonCollege/jc-theme-2015/files/1478947/codecanyon-18564931-gravity-forms-encrypted-fields.zip)

**Comment by banksashleym** [comment]
Hello! If there is any way we can get this plugin installed asap on the site that would be great. I just met with our IT department and she said that we are out of compliance with having non-encrypted data being stored on a server. Thanks so much, let me know if I can help with anything!

**Comment by joelworsham** [comment]
Absolutely!

**Comment by banksashleym** [comment]
Awesome, thank you so much!

**Comment by joelworsham** [comment]
So I have it installed and did some setup. What I need from you is to go through **every** form and turn encryption on for each field that should be encrypted. The way this plugin works is that only fields you explicitly tell it to encrypt will actually encrypt. To do so:

1. Navigate to the form edit screen for the desired form
2. Expand the field you wish to turn encryption on for
3. Click on the "Advanced" tab
4. Check "Encrypt field value" (see screenshot below)
5. Repeat steps 2-4 for each field to be encrypted in the form
6. Click "Update" to save the form
7. Repeat steps 1-6 for ALL forms that need encryption

![](https://d.pr/i/H7Zzq8+)

Once you have done this, please note that all previously submitted forms will not have their data encrypted. Once you have set up which fields should be encrypted, I will use a tool that comes with the plugin to retroactively encrypt all past submitted data, for which the field has encryption on. So I need you to let me know here when you've finished the above steps so I can perform this action.

I think that about does it!

**Comment by banksashleym** [comment]
Oh thank you so much! I have gone through the forms and set our restricted data fields to “encrypted” so this should be all set. I appreciate it!

Ashley Banks
Graphic/Web Designer
P  517.796.8465
F  517.796.8633
E  ABanks@jccmi.edu<mailto:ABanks@jccmi.edu>

[90 logo email signature]

Jackson College
2111 Emmons Road
Jackson, MI 49201

**Comment by banksashleym** [comment]
GAHH! I’m so sorry, I was restoring a backup of the staging and I mistakenly restore the production instead ☹ Now when I go to the live side it doesn’t have the encryption plugin…Could you push the most recent version to live again? I’m so sorry…

IT wanted me to remove the data from the WP servers for the forms that had SSN fields…So I exported the data as csv and removed on both the live and staging. But now they needed one more piece of info so I had to restore the staging with the data to retrieve what they were looking for and mistakenly restored live.

WHAT A CLUSTER! Lol - I appreciate all of your help

Ashley Banks
Graphic/Web Designer
P  517.796.8465
F  517.796.8633
E  ABanks@jccmi.edu<mailto:ABanks@jccmi.edu>

[90 logo email signature]

Jackson College
2111 Emmons Road
Jackson, MI 49201

**Comment by banksashleym** [comment]
Although now that I'm looking at live, I don't think it did the restore - I'm still able to see content I added today. Sorry if I'm making things worse lol. I'm going to stop touching the website now :)

**Comment by joelworsham** [comment]
hahahah no worries! I'll go through next week and do the encryption of past fields, but every new entry should have those fields encrypted.

**Comment by banksashleym** [comment]
Thanks! I don't even though that it would be necessary to encrypt the past fields. I removed the sensitive data, and took the forms off line until this plugin is all set.

I just logged on and see though that the encryption option isn't available anymore so I must have done something to screw it up...could you push this feature back out to live?

**Comment by banksashleym** [comment]
Just got a call from IT, they are anxious about this :) I installed and activated the plugin on staging (I didn't do anything with the settings) and tested and it worked and didn't break the site, so I did the same for the live side. Everything seems to be working so I think I can close this one? Thanks for all of your help!!
