### ISSUE TITLE
Remove "Read More" buttons from news/profile archives

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#198]
These are showing an error in accessibility as well. Thanks!

**Comment by joelworsham** [comment]
What error is showing? We could fix the error, rather than totally ditching them; unless, of course, you have other reasons for a better user experience without them?

I don't see an error in the WAVE tool: 

![](http://d.pr/i/DM2IxE+)

**Comment by banksashleym** [comment]
I'm finding that I'm having to use a few different tool alongside each other to catch all the errors unfortunately! The problem with the "read more" links is that the link text is non-distinguishable, and also that the button link and the title link are pointing to the same place, giving me a "redundant link" error as well! I have read that sometimes people using screen readers will pull just a list of links on a page, and this would pull a large list of "read more" instead of distinguishing the news story. 

I think this issue would be fixed by just removing the button altogether, even though I really like the look of it. 

![capture](https://user-images.githubusercontent.com/15264315/31830578-a592df74-b58e-11e7-8242-3911d29063bf.JPG)

**Comment by joelworsham** [comment]
I'll look into seeing common solutions for this. I'm guessing some `aria` attributes could help distinguish it, but research may show best scenario is to remove it.

**Comment by joelworsham** [comment]
I've done 2 things to resolve these errors:

1. Remove the redundant link by unlinking the title. The only link is now "Read More", which is fine considering it is the actionable item.
2. Add `aria-labelledby` attribute to the "Read More" buttons pointing to each article title. This way, screen readers will see that each "Read More" button apply to each article title.

Let me know if those errors clear up!
