### ISSUE TITLE
Language code on website: Accessibility

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#200]
More accessibility :) I am getting an error on each page saying the "document has invalid language code"

 Line 3, Column 1: Document has invalid language code.
<html lang="en-US" prefix="og: http://ogp.me/ns#" class="no-js"> <head> <meta charset="UTF-8"> <me...

Repair: Add a valid 2 letter or 3 letter language code as defined in the ISO 639 specification to the HTML 'lang' attribute. For XHTML, both 'lang' and 'xml:lang' must be set.

If you could look into this that would be great!

**Comment by joelworsham** [comment]
Hmmm this is odd. I have the default setup for WordPress for the language attributes:

![](http://d.pr/i/axCgVB+)

And I see them output on the live site:

![](http://d.pr/i/79qykv+)

So, my follow up questions would be:

- What tool is showing this error?
- Exactly what page(s) is this error showing on?
- Is more than one tool showing this error?

**Comment by banksashleym** [comment]
I believe this was with SiteImprove checker, but now it's not showing up...weird :) you can disregard this one and I will open it back up if I see this error again. Thanks!!
