### ISSUE TITLE
Update styling of events calendar

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#201]
hello! I am going to be adding quite a few more accessibility issues unfortunately - now that we have receive the DOE letter we are under to gun to get all accessibility issues resolved! 

I downloaded the NVDA screen reader and on the website homepage as I go through the events list the screen reader reads "View" "View" "View" as it moves through the events. Currently when you click on an event, the view button slides in and then you click the "view" link. Instead, could we style the events so that instead of the view button popping in you just click right on the event title? I'm thinking that would fix the screen reader issue, and that it would be reading the actual event instead of reading "view"

I'm bummed though because I love how this looked!!

**Comment by joelworsham** [comment]
No problem! Unfortunately, it is not uncommon to compromise on aesthetics for the sake of accessibility. Especially given the nature of the website, a federally funded college, accessibility is **key**.

I'll make this happen!

**Comment by banksashleym** [comment]
I agree, it's a bummer but definitely a necessity!
