### ISSUE TITLE
Alt text for news/profile/archives pages aren't showing up

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#203]
Hello! The alt text on banner images for the [news](https://www.jccmi.edu/news/) pages, [profile ](https://www.jccmi.edu/profiles/)pages, [Events](https://www.jccmi.edu/events/) section and [spotlight](https://www.jccmi.edu/jc-spotlight/) is showing an error on the accessibility scanner even though there is alt text on the image.

Thanks!

**Comment by joelworsham** [comment]
Actually, this needed some repair. The image was output manually with no attributes previously.

I updated the system to use the WordPress function `wp_get_attachment_image()` to do the heavy lifting. It now adds all attributes including: `width/height`, `class`, `alt`, `srcset`, and `sizes`.

Let me know if this corrects the error!
