### ISSUE TITLE
Ability to change "learn more" text on landing grid pages

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#207]
Hello,
on pages like [Financial Aid](https://www.jccmi.edu/financial-aid/) where we have the landing grid template enabled and you hover over the box, would it be possible to be able to input the text for link instead of it automatically generating "learn more"? These links are not distinguishable to a screen reader and coming up with an error. Thanks!

**Comment by joelworsham** [comment]
I added another field in the Landing Grid called "Button Text":

![](http://d.pr/i/FAprQm+)

This defaults to "Learn More", but you can edit it for each item.

**Comment by banksashleym** [comment]
Amazing! Thank you!
