### ISSUE TITLE
Accessibility: Add table header to courses table

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#212]
In our program pages, I list various the various course tables. Could we add a table header "Course Name" above the name of the course (there is currently no header) and change "Course" to "Course #"

For example, on [this page](https://www.jccmi.edu/degree/associate-degree/) the header above ENG 131 would be "Course #" and the header above Writing Experience I would be "Course Name"

Thanks!

**Comment by joelworsham** [comment]
Boom.

![](http://d.pr/i/HpXcGP+)

**Comment by banksashleym** [comment]
Perfect! I appreciate it!
