### ISSUE TITLE
alert pop up - adjust to show every time user accesses page

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#213]
Could the pop up alerts be adjusted so that they show up every time a page is accessed? For instance, for our [testing lab](https://www.jccmi.edu/testing-lab/), they want to publicize the thanksgiving hours. When I went to the page the first time the pop-up showed up, but then when I went to the page again it didn't show up until I cleared by cache. 

Thanks!

**Comment by joelworsham** [comment]
I can definitely add this feature.
