### ISSUE TITLE
Accessibility: change styling of pathway page

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#215]
Hi Joel,
Could we have the default style for the [pathways page](https://www.jccmi.edu/academics/programs-of-study/) to be that of the "landing grid" look instead of the "content" grid? I am coming up with contrast error for this one. The styling is built right into the pathway plugin. I was in the middle of just making the pathway page template the landing grid, but then I couldn't select the specific pathway page in the selection. 

Anyway, if it could look like how we have the [Campus Tour](https://www.jccmi.edu/locations/) boxes that would be great, where I could have the option of still choosing the colors for each pathway.

Thanks!

**Comment by joelworsham** [comment]
I think that I hit this? Could you do me a favor and check it out? Thanks!

**Comment by banksashleym** [comment]
Yes, this has been completed!
