### ISSUE TITLE
FAQ Site Editors select their assigned categories

### ISSUE THREAD

**Issue by joelworsham** [JacksonCollege/jc-theme-2015#216]
If the site editor has 1 available, auto-assign. If they have more than one, give them the option to choose.

**Comment by joelworsham** [comment]
@banksashleym  Alrighty, got this setup.

When a Site Editor creates a new FAQ, they can assign a topic from all topics they have access to. If they only have 1 topic, they cannot change it.

If a Site Editor has access to more than 1 topic, and they edit an already existing FAQ, and change the topic, you will be able to see this when approving the revision. There will be a box under the 
Approve/Deny box that denotes the current Topic. If the topic has been changed, it will say "Topic changed from Old Topic TO New Topic".

Let me know how this all works for you!

**Comment by banksashleym** [comment]
Hey Joel! I just got a call and it looks like our FAQ’s are not working correctly? I just checked my dashboard and the FAQ tab isn’t there anymore?
Any chance you could look into this?

Thanks!
Ashley

**Comment by banksashleym** [comment]
Nevermind on the previous email! I just re-activated the plugin and the FAQ’s popped in ☺

Thanks! I will test this out – this is great!

**Comment by joelworsham** [comment]
Ah okay, sorry for the confusion!
