### ISSUE TITLE
Additional Fields for staff directory

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#223]
Could you add a few more optional fields for the staff directory? If you could add Office Location and Office Hours that would be great! For the office location, I would like to not have the words "Office Location" show up, just the field contents like the others. But for Office Hours if we could have a drop down like the "more info" that is currently there that would be great!. and if there could be sub fields for the semester and days of the week? (Monday: Tuesday: Wednesday: ) I think that look cleaner and be easier to input.

And if both of these fields could be optional that would be great too. I'm adding the office hours just for faculty so it will just apply to them (right now we are linking to pdf's of their office hours and they look awful!)

Also, is there a way to add an additional optional misc field? There are a few of our faculty that want to display the link to their Youtube channels and right now I have them tacked on to their phone field and it looks bad.

This isn't a big rush, I would like to get the accessibility errors taken care of first if we could - just thought I would track this while I was thinking about it.

Thanks!

**Comment by joelworsham** [comment]
With the "Bio" field, do you still see the need for a "misc" field? I figure perhaps they could add things like youtube links to the bio field.

**Comment by joelworsham** [comment]
Actually, scratch that. I will add an optional misc field that is repeatable. That would work nicely

**Comment by banksashleym** [comment]
Sounds good, thanks!

**Comment by joelworsham** [comment]
All set! I added a repeatable, miscellaneous field as well. They can add any number of generic text fields.

**Comment by banksashleym** [comment]
Is there a way I can add the office hours field only to certain staff? Our faculty are really the only ones that would have office hours for students, and I'm noticing that when I update a non-faculty person the "View Office Hours" tag is coming up under their name without any information. Thanks!
https://www.jccmi.edu/financial-aid/financial-aid-staff/

**Comment by joelworsham** [comment]
Ah shoot, I see there was an error in the logic for this. I have corrected it so that it will not show unless there is any information input.
