### ISSUE TITLE
Form Spam

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#226]
I've noticed lately that we are getting "test accounts" as entries into our forms entries - mostly the four campus tour request forms. They look like spam. Our Admissions dept. has a link in the header "Request Info" that links to a third party new student inquiry form and she has also mentioned that she has receiving multiple test accounts as well. I enabled Akismet anti spam - but not sure if that's the right thing to do? I also added a captcha field to each form and enabled the "honeypot" anti spam in each form as well. 

Thanks for any info you can provide!

**Comment by joelworsham** [comment]
Those are all great things to do and guaranteed to lessen spam. Let me know if spam still finds its way through!
