### ISSUE TITLE
Accessibility: Page must contain one landmark

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#228]
Hello! I'm seeing a new error after the upgrade that is showing up on all pages:

"Page must contain one landmark"

Description:
Each page must have at least one main landmark, used to identify the main content. A main landmark provides a navigation point to the primary content of the page for users of assistive technologies.

Thanks!

**Comment by joelworsham** [comment]
Fixed in d986d22

**Comment by banksashleym** [comment]
Thanks! I am now getting an error saying that "main landmark is not a top level"

To solve - fix the following:
main landmark is contained in another landmark

Go figure!

**Comment by joelworsham** [comment]
MM yes I understand now what this is referring to. I setup the 3 top-level landmarks for header/content/footer. let me know if this clears up! (after theme is updated later)

**Comment by banksashleym** [comment]
Yes, this seems to be fixed now. Thank you!
