### ISSUE TITLE
Breadcrumbs missing

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#229]
Me again! I just noticed that the breadcrumbs are gone after the upgrade/switch. This isn't a big deal, just wanted to note it after I noticed it so I didn't forget.

Thanks!
Ashley

**Comment by joelworsham** [comment]
Oh shoot, I'll get right on this!

**Comment by joelworsham** [comment]
Somehow, the breadcrumbs were disabled via the Yoast SEO -> Advanced -> Breadcrumbs page:

![](https://d.pr/i/3c0qLv+)

I've turned it back on. Can you double check you're happy with the styling? Thanks!

**Comment by banksashleym** [comment]
Looks good! If you could replace the double arrows with a forward slash that would be great.

Thanks!

**Comment by joelworsham** [comment]
THis got turned off again... quite odd. Can you think of any reason? Only reasons I can think of:

- But with Yoast (possible)
- Someone other than me changed it
- Someone reverted to a backup

**Comment by banksashleym** [comment]
Hi Joel,
Yes, i actually turned it off this time! Dotty was looking through the 90th anniversary pages and mentioned that the breadcrumbs took away from the look of the pages so i turned them off temporarily until we get the content moved to a new subsite :)

**Comment by joelworsham** [comment]
Ohh okay. So, should they remain off entirely for now?

**Comment by joelworsham** [comment]
I've got the separator fixed for when we turn it back on.
