### ISSUE TITLE
Lost ability to add widget to right sidebar

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#235]
Hello! I have a few pages where I have enabled the right sidebar and pulled in events from the events calendar. Usually when I enable the right sidebar a new widget area is created "section:right (page name)" but nothing seems to be showing up in the widgets anymore when I enable a right sidebar section.

After the update to Foundation, any time I update a parent page it's almost like it strips off any changes I have made previously? For instance, on the [Student Life](https://www.jccmi.edu/student-life/) parent page I have enabled the right sidebar with events. However, when I go to the widgets area its no longer showing up in my list of widget areas, it's down at the bottom as "inactive sidebar (not used)" even though it is still functional on the site. 

Sorry for not catching this before - I was trying to add a new right section to a page and noticed that I was not seeing the widget areas. In the widget area, it only moves the widget to "not active" when I go to the parent page and make a change. There are 4 "inactive sidebar" items when they are actually still active. There is one that is still active "section(right): Financial Aid & Cost" but I think that's there only because I haven't made a change to that parent page. If i open that parent page up and make a change it would then move the widget area to the inactive area.

Sorry if this doesn't make sense!

**Comment by joelworsham** [comment]
Well, this isn't good! So sorry for this. I'll get to the bottom of this ASAP and get it fixed up.

**Comment by banksashleym** [comment]
Thanks!

**Comment by joelworsham** [comment]
I believe this one was fixed when I updated Field Helpers fully. Can you do me a favor and verify or deny this? Thanks!

**Comment by banksashleym** [comment]
Yes, this seems to be working now, thanks!
