### ISSUE TITLE
Staff plugin: New entries are listed in the dashboard as "Auto Draft"

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#236]
I added a new employee yesterday, and everything looks good on the website, but he is listed in dashboard as "Auto Draft" instead of by his name.

**Comment by joelworsham** [comment]
Ah yes. SOrry for this. Incompatibility I missed from the updated FIeld Helpers plugin. They will work now.

I notice that there is an Auto Draft with no information filled out, except for the "History" department being selected. You may want to check that one: https://www.jccmi.edu/wp-admin/post.php?post=22775&action=edit

**Comment by banksashleym** [comment]
Thanks! Yes, yesterday I tried to add a new staff member but none of her information except for the department was saving. I just tried and it's working now, thank you!
