### ISSUE TITLE
Dashboard field areas very small

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#237]
This isn't a big deal, but on a lot of pages in the dashboard, the field areas are now very small? This is happening on program pages, staff entries and a few other areas.

![capture](https://user-images.githubusercontent.com/15264315/36486997-e40d2762-16ed-11e8-8fc1-c68841d007ae.JPG)

**Comment by joelworsham** [comment]
Fixed by updating RBM Field Helpers to latest.
