### ISSUE TITLE
Audience tabs on home page missing images

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#240]
Good morning, when I went to our home page this morning I noticed that the audience tabs are missing their pictures? I edited the home page and the option to add the image back in seems to be gone. Thanks!
![capture](https://user-images.githubusercontent.com/15264315/37287022-1208ac18-25da-11e8-8a4f-ad575e510d91.JPG)

**Comment by joelworsham** [comment]
Found the issue. It was another incompatibility with a recent update. Apologies again. I've got it restored and the images working again.

**Comment by banksashleym** [comment]
Thank you!
