### ISSUE TITLE
Preview button for developers

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#242]
Hello! Would it be possible to add a preview button for developers in the "Submit" area so that when they are updating a page they can preview before they submit their revision? Currently there is only an option for Submit for Review and Save Draft. 

I have a web liaison committee meeting tomorrow 4/10 at 1:30 p.m. - I'm not sure if this is a quick add or more time consuming, but if this could be incorporated by then I would greatly appreciate it! Thanks!

![capture](https://user-images.githubusercontent.com/15264315/38506041-c040387e-3be6-11e8-9844-bdabe80552a7.JPG)

**Comment by banksashleym** [comment]
Thanks Joel, no biggie! I remember requesting this a while ago and you did do some work on it. There is a "view page" link in the toolbar that I showed them and that allows them to preview the page. We can still keep this on the list because I think it would be nice for them to have the preview button in the submit area but we can move it down the list and work on more priority projects. I would love to tackle all of the accessibility areas first if we could. I appreciate it!

**Comment by joelworsham** [comment]
I'm not sure if this is exactly what you wanted, but I added a preview button that will appear when they save their revision as a draft. So they can "Save Draft" without pushing the revision for review, then the can click a new "Preview" button.

![](https://d.pr/i/FZBqyO+)

**Comment by joelworsham** [comment]
Let me know if this is sufficient. Thanks!

**Comment by banksashleym** [comment]
This is perfect, thanks!
