### ISSUE TITLE
Accessibility: Use unique identification for elements

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#244]
This one is coming up for the text links below the two secondary news images. Same thing, I think it might be that they both have an ID that is the same: #home-news-5.

1.3.1 Info and Relationships
The ID used for an element on the page is also used for another element on the page. ID's must be unique.

Thanks!

**Comment by joelworsham** [comment]
I believe this will be fixed once #243 is closed (so I will close this one now).
