### ISSUE TITLE
Form managers now have access to all forms

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#245]
Hello,
I received an email today from a person in Financial Aid who should only have access to financial aid forms. She said when she logged in she now has access to all forms. I logged in as her and a few other developers and it seems like all users with the role "forms manager" have access to all forms, where before I would assign them a form.

Thanks for checking in to this!

**Comment by joelworsham** [comment]
Oh no... sounds like something may have changed within Gravity Forms. I'll put this at the top of the list.

**Comment by joelworsham** [comment]
This was in fact due to a slight change in Gravity Forms now conflicting. All fixed! (changes won't be live for about an hr)
