### ISSUE TITLE
Programs of Study page

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#246]
This is not so much an issue, but more of an enhancement. I was going through our programs of study and feel like we might be able to eliminate a click in to view programs by dynamically listing/filtering all of the pathways and programs on the main [program page](https://www.jccmi.edu/academics/programs-of-study/) versus having to click into each pathway and then viewing all of the programs within the pathway. 

I would love to be able to view all programs, and then be able to filter out the programs based on their pathway, very similar to how [this college](https://www.pcc.edu/programs/) does their programs page, where the pathway icons are at the top and you can filter/view either all of the programs or choose by pathway. Their mobile version of this page is great as well.

I put together a demo of kind of what I'm thinking about. Let me know if something like this could be accomplished with our weekly hours (I don't mind taking a month's worth) or if this is more of a special project. Thanks!

![programs](https://user-images.githubusercontent.com/15264315/39255177-e799a49c-4879-11e8-8940-305cd3095759.jpg)

**Comment by joelworsham** [comment]
This would be nice! This rework of the hierarchy display would probably be classified as a "small project". Chipping away at this 1hr a week would be fairly inefficient and would take away from other ongoing weekly tasks.

I'll talk to Steve about it for exact numbers, but this would be a very beneficial project!

@BigActual

**Comment by banksashleym** [comment]
Sounds good! The reason why I ask is that Dotty is finalizing her budget for the upcoming fiscal year and I don’t think there is any additional money for the web related items above the $5000 support agreement so I’m thinking this would be the only way to get this one done. I’m not sure if this one would take more than 4 hours ( a month’s time we have allotted) but I’m willing to forego any issues for a month when we get to a point where any priority issues have been completed :) Let me know your thoughts!

**Comment by joelworsham** [comment]
Hey there Ashley. Sorry for the delay.

I talked with Steve about it. Optimally, we could do this project in tandem with maintenance tasks at an increased hourly rate, but we understand the budget is what it is for now.

That said, I plan to get the work for this done ASAP, doing it all at once, and then offset maintenance tasks for however many hours it takes. I anticipate between 4-8 hours, or 1-2 months of maintenance, but who knows, maybe it will move quickly! Just need to make sure it gets done right and I'm able to add some time for testing.

I'll message back here when it's done and put it on staging for you to review!

**Comment by banksashleym** [comment]
That would be great, thank you so much :) I appreciate you guys working with us and being so flexible. I'm hoping in the future I can make the case for keeping a budget especially for special projects like these.

**Comment by joelworsham** [comment]
@banksashleym how do you envision the "View All" working? Would it essentially show all tabs stacked? So:

PATHWAY TITLE & DESCRIPTION
[LIST]

PATHWAY TITLE & DESCRIPTION
[LIST]

PATHWAY TITLE & DESCRIPTION
[LIST]

OR, would you want just a list of all programs alphabetically? This would omit each pathway title and description.

**Comment by banksashleym** [comment]
Ideally, I would like to list the View All alphabetically - but somehow incorporate an icon for each where you can still see which pathway they are in?

**Comment by joelworsham** [comment]
I have the first draft pushed to the staging site and I have set the page template for the Programs of Study page to "Pathways". Please take a look and let me know!

Here's what needs to happen for the system to fully work:

- Each Pathway must be customised. You set the Image and Color under "Pathways Template"
- The Programs of Study page should have the "Pathways Template Settings" Image and Color set for "View All Programs"
- Each program must have the Pathway parent set. This is because the theme is built with a one-way relationship. So, the pathway knows its programs, but the program does not know it's pathway. This was programmed this way because it was all that was needed for the theme. This means that when I list all the programs, each program cannot show which pathway it belongs to. So, you will need to go into each program and set the pathway. Perhaps in the future we can improve the relationship between pathways and programs, but that would add a bit too much time to this project right now.

I think those 3 steps above are all that's required.

Let me know your thoughts!

**Comment by banksashleym** [comment]
You have seriously outdone yourself - this is so dang cool!! 

Not sure if this is possible, but instead of below each program, could we put the icon and pathway to the right of the description (like create a column on the right so it mirrors the big buttons at the top where the icon is on the top and pathway is listed below that?) I love how it looks on mobile where it's below the description. Let me know your thoughts! I will start customizing all of these :)
![68747470733a2f2f642e70722f692f49704a6454492b](https://user-images.githubusercontent.com/15264315/40019015-f8ab70f0-578b-11e8-9b95-cdc2aaf01791.jpg)

**Comment by joelworsham** [comment]
Yeah I can definitely do that! Although, it won't look exactly like your mockup. You're going to be (and currently are) using custom images for these, instead of actual icons. This means the colors cannot be customized like they can be with true icon fonts.

So, you will need to try to use an image that looks good both in the "tabs" as well as to the side of these. I think that if you were to take that heart image you just posted and change the color to the exact color you set each Pathway to, it would look good in both. Just make sure the heart itself is white and not transparent.

**Comment by BigActual** [comment]
If these were .svg, couldn't we style them?

**Comment by joelworsham** [comment]
I typically avoid using SVG's in the media manager. Typically I will use those inside of a theme or plugin itself.

I do think we can make this look good with PNG's though.

**Comment by banksashleym** [comment]
YESS! This is perfect!

**Comment by joelworsham** [comment]
I've got it on staging now. Please take a quick glance and make sure you're happy with it. Once we decide it's good to go, I'll push it over to live!

**Comment by joelworsham** [comment]
Hey Ashley! Any chance you've been able to verify we're ready to rock and roll and push this thing to live?

**Comment by banksashleym** [comment]
Hello! I am just finalizing adding the colors and icons and they look great! Just a few questions/suggestions
- When you hover over the icons, could we match the border color to the icon instead of having it maroon? So on business it would hover blue, health would be the red, etc? Sorry I'm picky lol
- Is it possible to make icons and text smaller in right column on view all? if we can make it so there is no white space under the images that would be great. 
- could we make the icons at the top of the page in the same position across all boxes? (business & computer and Science & Math are in a different spot because of them being two lines)
On mobile: 
-Is it possible to remove the pictures of each program and put the title, description and pathway icons below the description and side by side? It just seems like a lot to scroll through :)
-could we center the icon and the name relative to the height and decrease the vertical padding a little? On my phone when you click on the different pathways you don't notice that below the programs are changing.

I think that's it! Once these changes have been made I should probably forward these on to our pathway committee for their final approval before we go live. I appreciate it!

**Comment by joelworsham** [comment]
Apologies, this last comment somehow slipped past my radar. I'll hit it ASAP

**Comment by BigActual** [comment]
@joelworsham - Could you please push these changes up for Ashley? Looks like there was a snafu and I'd like to have her review this with her team as soon as possible. Thanks.

**Comment by banksashleym** [comment]
No worries at all! Even if it gets pushed sometime this week that would be great, there isn't a huge rush.

**Comment by joelworsham** [comment]
I definitely agree the mobile view is stuffed up, but can you please clarify exactly what you mean by:

> put the title, description and pathway icons below the description and side by side?

I don't quite understand the layout you are describing

**Comment by joelworsham** [comment]
Hey @banksashleym . Just wanted to make sure you've seen this. I'd love to get it closed! Thanks!

**Comment by banksashleym** [comment]
Hi Joel, yeah after reading that back that does seem confusing. Here is what I was thinking. Removing the pic on mobile and instead of the pathway icon being stacked could we style it so that the icon portion is smaller and the text is bigger and left justified so that it fits in the space  better? I think if it is the stacked version on mobile a user would have to do a lot of scrolling to get through the whole list. Let me know your thoughts!
![programs](https://user-images.githubusercontent.com/15264315/42769460-3006831a-88f0-11e8-9ae6-6e1c8ea1ed0a.jpg)

**Comment by joelworsham** [comment]
@banksashleym all set! Let me know what you think.

**Comment by banksashleym** [comment]
This looks awesome!! The only thing I see is on desktop now the pathway icons are sitting below the paragraph description? Can we move these back up to be in a column to the right of the paragraph description?

**Comment by joelworsham** [comment]
Oh... yes, that was not supposed to be the case, I think something didn't get pushed up to the server right.  Just re-pushed and refreshed and it looks proper again!

**Comment by banksashleym** [comment]
This looks so good!! I'm going to forward on to the pathways committee for their approval before we go live if you don't mind. I will let you know asap when we are ready!

**Comment by banksashleym** [comment]
Good morning, this new programs of study page has been approved by our pathways committee! Before we go live I just have one question. Will I be able to update the links in the main navigation (see below) to the filtered view in the new programs page instead of taking them to the standalone pathway page? For instance, if a student clicks on the "Business and Computer" link in the main nav, could it go to the "business and computer" filtered list in the new programs page? When I hover over each program tab in the new programs page I do see that there is a link "/academics/programs-of-study/#jc-pathway-tab-3271" but when I try to set that link in the main nav links it still goes just to the main programs page.
 Thanks for any info you can provide!
![capture](https://user-images.githubusercontent.com/15264315/43464059-14f08472-94a8-11e8-857b-1b7a750b6766.PNG)

**Comment by joelworsham** [comment]
Yes absolutely. This functionality can be added! I'll do that soon and let you know.

**Comment by joelworsham** [comment]
I've got this setup! Click on each tab to get the proper URL to link to.

**Comment by banksashleym** [comment]
THIS IS PERFECT! I love it, we are good to publish to live! Thank you so much :)

**Comment by joelworsham** [comment]
Pushed up to live!

**Comment by banksashleym** [comment]
Thanks! I'm assuming it will take a while? I'm not seeing it yet but I'll give it a while before I check again :)

**Comment by joelworsham** [comment]
Well, to be clear, I only pushed the code. You will still need to reformat the page and setup the Pathway icons/colors. There is, unfortunately, no easy way to "migrate" only that page from staging to live.

**Comment by banksashleym** [comment]
Oh gotcha! That makes sense :) I appreciate it - everyone just loved this new layout

**Comment by joelworsham** [comment]
Glad to hear!
