### ISSUE TITLE
Not able to change spotlight images

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#247]
Hello, I went to go and switch out our Spotlight images and when i go to spotlights and try to add an image, there isn't an option to add the image. Thanks!
![capture](https://user-images.githubusercontent.com/15264315/39376504-e9c3b13e-4a1f-11e8-842f-5cd385de7775.JPG)

**Comment by joelworsham** [comment]
Oh no! sorry for this... let me get this one ASAP

**Comment by joelworsham** [comment]
All set!

**Comment by banksashleym** [comment]
Thank you so much!
