### ISSUE TITLE
Not able to add degree to program page

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#248]
Hello! I just added a new program "Cloud Computing" and I now don't have the option to add a degree into the program. However when i go to the Cloud computing program page, under "Jackson College offers the following degree options:" all of the degrees are showing up.

Thanks for looking in to this!

**Comment by joelworsham** [comment]
Gah yes, my fault again. I see the issue with adding new Programs.

All fixed!

**Comment by banksashleym** [comment]
Thank you!
