### ISSUE TITLE
Spring Cleaning - Database Edition

### ISSUE THREAD

**Issue by joelworsham** [JacksonCollege/jc-theme-2015#252]
I pull down the database from the live site to my local site every week, so I consistently get a get overall view of the size of the JC database, and let me tell you, it's large :P

Of course, Jackson College is going to inherently have a large website and database; there is a lot of information. But I believe I see some places we could trim the fat. Minimizing the size of the DB will help:

- Overall query times, which of course helps page load times on both the front and back end
- Backup management in terms of space needed and time taken to do it
- Development related processes, like me bringing down the site each week
- Did I mention page load times?

It's just a good thing to do every now and again.

So, I'd like to work with you to identify what can go and what can stay. My advice will be things like "only store the last 12 months of form submissions". We can also make sure to simply store (offsite) a dump of the database before cleaning it up, this way there is no risk of lost data.

I can (and will) provide a list of recommended fat trimming areas and I'd love if you could let me know your thoughts (and precautions) on each one!

Thanks, @banksashleym !

**Comment by banksashleym** [comment]
Awesome!! I was actually going to talk to you about this, specifically with our media folder. We have a ton of stuff in there (pictures, pdfs, etc..) I make it a point that when I'm deleting something from the website to delete the actual file in the media library, but I know a lot of developers don't do that. Is there a way we can do an audit of media files that are currently used/not used? I think we can free up a ton of space there. Also, I agree with the form submissions. I can go through those and purge a lot there as well. Let me think of some other things we can get rid of as well.

Thanks!

**Comment by joelworsham** [comment]
Definitely! I think the media would be best as another issue, because the solutions will be quite different. There are certainly plugins out there can aid in auto-detecting if any media is truly unused, and delete it.

We can also look into tools that "smush" down the size of media files by stripping meta information on each file. Only saves a few KB per file, but when you have 1000's of files, that's now MB. 

Anyways, yes let's open another issue to discuss that!

**Comment by banksashleym** [comment]
Closing this as well as I am currently purging form data/media files.
