### ISSUE TITLE
Spring Cleaning - Media Edition

### ISSUE THREAD

**Issue by joelworsham** [JacksonCollege/jc-theme-2015#253]
From DB cleaning issue - 

> Definitely! I think the media would be best as another issue, because the solutions will be quite different. There are certainly plugins out there can aid in auto-detecting if any media is truly unused, and delete it.
> We can also look into tools that "smush" down the size of media files by stripping meta information on each file. Only saves a few KB per file, but when you have 1000's of files, that's now MB.

We can continue to post more ideas and general discussion here.

**Comment by banksashleym** [comment]
I'm going to close this issue as I'm currently doing a purge of all of the unused media on the website.
