### ISSUE TITLE
Improve image optimization for page load speed improvement

### ISSUE THREAD

**Issue by BigActual** [JacksonCollege/jc-theme-2015#254]
There's a rather long list if one cares about "scores" but the meat of optimization would come from optimizing the size of the following items. Let's take care of them in the next maintenance cycle, please?

- Losslessly compressing https://www.jccmi.edu/wp-content/uploads/90-logo-FINAL.jpg could save 567.6KiB (79% reduction).
- Losslessly compressing https://www.jccmi.edu/wp-content/uploads/cloud-networking.jpg could save 25.1KiB (19% reduction).
- Losslessly compressing https://www.jccmi.edu/wp-content/uploads/Rose-Run-web-240x300.jpg could save 14.4KiB (37% reduction).
- Losslessly compressing https://www.jccmi.edu/wp-content/themes/jc-theme-2015/dist/assets/images/header-logo.png could save 5.2KiB (36% reduction).
- Losslessly compressing https://www.jccmi.edu/wp-content/uploads/CCE.jpg could save 1.4KiB (11% reduction).

Here's all the rest, if bored, it's the tiniest bit helpful.

- Losslessly compressing https://www.jccmi.edu/wp-content/uploads/Current-Student.jpg could save 919B (7% reduction).
- Losslessly compressing https://www.jccmi.edu/wp-content/uploads/Alumni.jpg could save 903B (6% reduction).
- Losslessly compressing https://www.jccmi.edu/wp-content/uploads/Employees.jpg could save 902B (5% reduction).- Losslessly compressing https://www.jccmi.edu/wp-content/uploads/spotlight-25.jpg could save 1.2KiB (1% reduction).
- Losslessly compressing https://www.jccmi.edu/wp-content/uploads/Spotlight-9.jpg could save 1.1KiB (1% reduction).
- Losslessly compressing https://www.jccmi.edu/wp-content/uploads/Spotlight-10.jpg could save 1.1KiB (1% reduction).
- Losslessly compressing https://www.jccmi.edu/wp-content/uploads/Spotlight-8.jpg could save 1.0KiB (1% reduction).
- Losslessly compressing https://www.jccmi.edu/wp-content/uploads/Spotlight-22.jpg could save 1014B (1% reduction).
- Losslessly compressing https://www.jccmi.edu/wp-content/uploads/Spotlight-5-1.jpg could save 1000B (1% reduction).
- Losslessly compressing https://www.jccmi.edu/wp-content/uploads/StudentGroup.jpg could save 991B (6% reduction).
- Losslessly compressing https://www.jccmi.edu/wp-content/uploads/Spotlight-6.jpg could save 988B (1% reduction).
- Losslessly compressing https://www.jccmi.edu/wp-content/uploads/Spotlight-4.jpg could save 981B (1% reduction).
- Losslessly compressing https://www.jccmi.edu/wp-content/uploads/Spotlight-30.jpg could save 970B (1% reduction).
- Losslessly compressing https://www.jccmi.edu/wp-content/uploads/MilitaryFriendly.png could save 956B (8% reduction).
- Losslessly compressing https://www.jccmi.edu/wp-content/uploads/Spotlight-21.jpg could save 944B (1% reduction).
- Losslessly compressing https://www.jccmi.edu/wp-content/uploads/Center-for-Student-Success.jpg could save 894B (1% reduction).
- Losslessly compressing https://www.jccmi.edu/wp-content/uploads/Spotlight-40.jpg could save 862B (1% reduction).
- Losslessly compressing https://www.jccmi.edu/wp-content/uploads/Budget_Transparency_Logo-e1490210142336.png could save 560B (2% reduction).
- Losslessly compressing https://www.jccmi.edu/wp-content/uploads/aacc-e1451327521131.png could save 121B (2% reduction).
- Losslessly compressing https://www.jccmi.edu/wp-content/uploads/mcca-e1451327460605.png could save 84B (2% reduction).
- Losslessly compressing https://www.jccmi.edu/wp-content/uploads/acct-e1451327594426.png could save 74B (1% reduction).
- Losslessly compressing https://www.jccmi.edu/wp-content/uploads/hlc-e1451327499507.jpg could save 32B (1% reduction).

**Comment by BigActual** [comment]
This is addressed generally in #253 Merge if appropriate.

**Comment by banksashleym** [comment]
Closing this as well.
