### ISSUE TITLE
#2 Broken links on news archives

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#257]
Hello,
Ran across a few more broken links on the news archive pages. At the bottom of the page are navigation links to go to more archives for the month and the "1" "2" and "Next" links all go to a 404 page. What are your thoughts on just removing the navigation feature at the bottom altogether and just have a long running list? It seems like this feature is only showing up on archive pages that have a lot of news stories:
https://www.jccmi.edu/2018/01/
https://www.jccmi.edu/2018/03/
https://www.jccmi.edu/2018/04/
https://www.jccmi.edu/2018/05/

Thanks!

**Comment by d4mation** [comment]
I have pushed a change for this to the Staging site (http://jacksoncollege.staging.wpengine.com/)

WordPress oddly doesn't natively support this, so I had to construct links for the Previous and Next Month's Archives manually.

Let me know if it's good to push Live! 👍

**Comment by banksashleym** [comment]
Thanks! As I'm checking, we don't have any releases for May so it's coming through with a broken link there as well down at the bottom...honestly, I don't have a problem just having one long list of the releases and eliminating this feature altogether?

**Comment by d4mation** [comment]
We should be able to do this. https://jacksoncollege.staging.wpengine.com/news/ works just fine chronologically going backwards, so we'd just need to disable the Yearly/Monthly breakdowns.

Does that sound good to you?

**Comment by banksashleym** [comment]
I would still love to keep the drop down news archive in the left side navigation to be able to view the news releases by month/year. It just seems like we are running into some broken links at the bottom of a few months (January 2018 I believe is one) where the releases from Jan. are broken up into two pages and when you click on the 2 to view the rest of the Jan. releases it comes back with a broken link. Could we still be able to filter via the drop down in the left menu by month but just show all releases that month in a big list versus break them up into multiple pages?

**Comment by d4mation** [comment]
So, while I was writing the code for this I rewrote the overall pagination code for the site a little bit and it turns out that it fixed the underlying issue for these 404s. Could you try the following pages on Staging to confirm? 

https://jacksoncollege.staging.wpengine.com/2018/01/
https://jacksoncollege.staging.wpengine.com/2018/03/
https://jacksoncollege.staging.wpengine.com/2018/04/
https://jacksoncollege.staging.wpengine.com/2018/05/

**Comment by banksashleym** [comment]
Yes, these now work! Thanks!

**Comment by d4mation** [comment]
This change is now Live 👍
