### ISSUE TITLE
Search submission brings up error

### ISSUE THREAD

**Issue by BigActual** [JacksonCollege/jc-theme-2015#261]
Someone just e-mailed Ashley saying that, "...our search feature on the website is doing something weird. When she types in "Student Services" she gets the following.

I have typed in a few things and some go to the right web pages and some search terms pull up the site below…search terms like "student services" "Transfer" "forms"

**Comment by banksashleym** [comment]
Hello! I actually think I just figured out why this was happening! There was a wp data table that was on a page that wasn't functioning properly so I removed the shortcode for the table and fixed the error and everything seems to be working now. Thanks!
