### ISSUE TITLE
Accessibility: Link text used for multiple destinations

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#262]
Hello, I'm getting an error in my accessibility scanner for all of our program pages saying that two links with the same name are going to two different destinations. One is the Link "Programs" in the main nav, and one is "Programs" in the breadcrumbs on the program pages. Is there a way to remove the Programs link from the breadcrumbs? It's really not needed because the link after that is Programs of Study which is perfect. The "programs" link in the breadcrumbs goes to a page that I've never seen before - basically just a listing of our programs. If we could somehow eliminate that one that would fix the error. Thanks!
![1](https://user-images.githubusercontent.com/15264315/45836835-dc9df800-bcdb-11e8-978a-7ddc291f8c09.PNG)

**Comment by d4mation** [comment]
I have pushed this change to the Staging site (http://jacksoncollege.staging.wpengine.com/)

Let me know if it's good to push Live! 👍

**Comment by banksashleym** [comment]
Hi Eric, this is perfect, thanks! This is good to push to live.

**Comment by d4mation** [comment]
This change is now Live 👍
