### ISSUE TITLE
Accessibility: Non-distinguishable landmarks

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#264]
Hello! I will be adding some more accessibility issues for this week. From the SiteImprove dashboard here is a summary of the description of the issue and a suggestion for how to fix.

**Description**
The page contains two or more HTML5 or WAI-ARIA landmarks of the same type that has not been named. Users might not know the difference if it's not somehow explained.

**How to fix it:**
Use the WAI-ARIA attributes 'aria-label' or 'aria-labelledby' to create unique names that describe the purpose of each landmark.

This error is showing up for all pages.

From the [siteimprove chrome extension](https://chrome.google.com/webstore/detail/siteimprove-accessibility/efcfolpjihicnikpmhnmphjhhpiclljc?hl=en-US) it seems to be highlighting the search and the three nav areas (see image below).

![1](https://user-images.githubusercontent.com/15264315/46360380-42be3f80-c639-11e8-9dbe-951b186e9f5a.PNG)

**Comment by d4mation** [comment]
This change is up on Staging. Could you check that it appears fixed on your end?

**Comment by banksashleym** [comment]
Awesome! Yes, the error is gone when I check the staging site.

**Comment by d4mation** [comment]
This change has been pushed to Live 👍
