### ISSUE TITLE
Accessibility: Redundant WAI-ARIA attribute

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#267]
A WAI-ARIA attribute that has the exact same features as the HTML element it has been applied to has been used. The WAI-ARIA attribute is redundant since is doesn't provide the user with any additional information.

For landmarks it has previously been a recommendation to use HTML5 and WAI-ARIA landmark roles together (e.g. WAI-ARIA role="navigation" on HTML5 'nav' elements) to maximize support, but with the widespread adoption of HTML5 this is no longer needed.

The WAI-ARIA attribute can be removed without any impact for end users. The result will be cleaner, easier to maintain code.

This error is highlighting the footer area and affects all pages.

![4](https://user-images.githubusercontent.com/15264315/46361395-831ebd00-c63b-11e8-87c6-62cd8e9fedf7.PNG)

**Comment by d4mation** [comment]
This change is now on Staging.

**Comment by banksashleym** [comment]
This looks good too!

**Comment by d4mation** [comment]
This change has been pushed to Live 👍
