### ISSUE TITLE
Library widget showing up twice

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#268]
Hello!
Our library contracts with a third party tool to provide a chat service. The company provide a script that I add to the page. It's been working fine until recently when the chat window has been showing up twice on the page.

https://www.jccmi.edu/library/chat-app/

Jen, a library staff member has been in contact with this company about this issue and they provided the following explanation:

Because Qwidget is resetting the window.onload function to allow multiple qwidgets,  if the client’s page is also doing something with the onload, it will have unexpected behavior.  This is the case with the double Qwidgets on the first page.

We load the qwidget once when the qwidget js file is loaded. Then their app.js triggers it again.

The team also sent details of where the code from the app.js file is causing the reload (code is below). The attached text document shows where the double load is happening. If you can edit this script, it should stop the Qwidget from loading twice on your page.

```
e.onLoad = function(t, e) {                        

var i = "complete" === document.readyState
                          , n = (i ? "_didLoad" : "load") + ".zf.util.onLoad"
                          , o = function() {
                            return t.triggerHandler(n)
                        };
                        return t && (e && t.one(n, e),
                        i ? setTimeout(o) : (0,
                        s.default)(window).one("load", o)),
                        n
                    }

```
If you could update the app.js file that would be great. Thanks!

**Comment by d4mation** [comment]
This was part of a vendor library so I had to get a bit creative with the fix (We can't just edit `app.js` as that is a compiled file which includes all vendor libraries and our own code into a single, smaller file). But it looks like it is indeed working properly now.

Could you confirm on http://jacksoncollege.staging.wpengine.com/library/chat-app/ when you get the chance?

**Comment by banksashleym** [comment]
This is perfect, thank you!

**Comment by d4mation** [comment]
This is now Live 👍
