### ISSUE TITLE
Accessibility: Main nav drop down on tab

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#270]
Hello!
I've been doing some manual testing on the site using my keyboard, and I noticed that as I tab through the site when I get to the main navigation it skips over the drop down menu's? If we could have it so that when someone tabs over "programs" the menu automatically drops down and then they can tab through all of the sub-options "Business & Computer, etc..." and then it would move to the "Academics" tab and so forth?

**Comment by d4mation** [comment]
I just pushed a fix for this to the Staging site.  👍

**Comment by banksashleym** [comment]
This looks great! Is there any way the focus could go down the column instead of across columns when the drop down opens? As it focuses now for example in the programs tab it's jumping from business to liberal arts then back to health...it's set up in the menu where I have to stagger the items to get them to be alphabetical in the column, so I can see why they are focusing across vs. going down the line.

**Comment by d4mation** [comment]
I pushed a change to Staging to accommodate this. However, it requires a slight change to the menus: they need to be changed to no longer be staggered to make them alphabetical. Instead, I wrote some code to re-arrange how they were displayed to make them read downward like they are now on Live but still be in-order within the page's code (When they were staggered, they were in-order on-screen but not in the page's code which is what tabbing through looks for).

This is generally better for accessibility and prevents us from having to manually define a tab-order: https://webaim.org/techniques/keyboard/tabindex#overview

**Comment by banksashleym** [comment]
This is great!! Thanks so much!

**Comment by d4mation** [comment]
This change has been pushed to Live 👍

**Comment by d4mation** [comment]
Don't forget that this will require you going in to rearrange the Menu to have each section be in actual Alphabetical Order rather than the Staggered setup it has now!

**Comment by banksashleym** [comment]
Thank you!
