### ISSUE TITLE
Accessibility: tabs shortcode

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#272]
Continuing my keyboard testing and whenever there is a page with the tabs shortcode I'm not able to tab through any of the tabs. It will show focus on the first tab, but then the focus will jump to the side navigation instead of jumping through each tab. 

For example, on the [internships page](https://www.jccmi.edu/internships/internships-student-information) when I start tabbing the focus goes from the breadcrumbs to the first tab "eligibility criteria" and then it jumps to "internships" in the left side navigation. Could we add the ability to use the tab to sift through each tab heading and then press enter to be able to view the contents?

Thanks!

**Comment by d4mation** [comment]
This change has been pushed to Staging 👍 

You can see it in action here: http://jacksoncollege.staging.wpengine.com/internships/internships-student-information/

**Comment by banksashleym** [comment]
Looks great! Thanks!

**Comment by d4mation** [comment]
This change is now on Live 👍
