### ISSUE TITLE
Accessibility: Non-distinguishable landmarks

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#273]
I'm getting an error on our programs of study page for non-distinguishable landmarks. the SiteImprove checker suggests using the WAI-ARIA attributes 'aria-label' or 'aria-labelledby' to create unique names that describe the purpose of each landmark. Thanks!

![capture](https://user-images.githubusercontent.com/15264315/47514319-123f7f00-d84e-11e8-881e-06ed39e3f604.PNG)

**Comment by d4mation** [comment]
This change is now on Staging 👍

**Comment by d4mation** [comment]
@banksashleym Have you had a chance to review this change? If so, I'll get this pushed to Live today along with #272 and #193

**Comment by banksashleym** [comment]
Sorry about that, I didn't see this one come through. Yes, this looks great - thanks!

**Comment by d4mation** [comment]
This change is now on Live 👍
