### ISSUE TITLE
Accessibility: Non-distinguishable landmarks for left navigation

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#274]
On pages where I have the left side nav enabled and also the events widget, i'm getting an error:

Description of this issue:
The page contains two or more HTML5 or WAI-ARIA landmarks of the same type that has not been named. Users might not know the difference if it's not somehow explained.

How to fix it:
Use the WAI-ARIA attributes 'aria-label' or 'aria-labelledby' to create unique names that describe the purpose of each landmark.

![capture](https://user-images.githubusercontent.com/15264315/47514501-8843e600-d84e-11e8-946d-6d76b64d95c4.PNG)

**Comment by d4mation** [comment]
This change is up on Staging 👍

**Comment by banksashleym** [comment]
Looks great!

**Comment by d4mation** [comment]
This change has been pushed to Live.
