### ISSUE TITLE
Accessibility: Non-distinguishable landmarks for programs/courses/news

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#275]
Also getting a non distinguishable landmark error for each of these content types:

- [news](https://www.jccmi.edu/news/)
- [degrees](https://www.jccmi.edu/degree/)
- [courses](https://www.jccmi.edu/course/)
- [profiles](https://www.jccmi.edu/profiles/)
- [Spotlights](https://www.jccmi.edu/jc-spotlight/)

Any time there is a page that lists multiple news/degrees/courses, etc..like an archive page -  SiteImprove is giving an error "The page contains two or more HTML5 or WAI-ARIA landmarks of the same type that has not been named. Users might not know the difference if it's not somehow explained." Thanks!

**Comment by d4mation** [comment]
This change is now on Staging 👍

**Comment by banksashleym** [comment]
These look great too!

**Comment by d4mation** [comment]
This change has been pushed to Live.
