### ISSUE TITLE
redirect http:// pages to https://

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#276]
Is there a way on the server to automatically redirect all non secure pages to secure? I have noticed that sometimes I will get emails from employees here at JC and they include links back to the website that aren't in the https format. I don't think a lot of people here would know that when they are typing in a url to put https://...is there a way to force a redirect so that all pages come through as secured?

Thanks!

**Comment by d4mation** [comment]
It looks like when #62 was handled, it was set up to only secure those specific URLs.

I have set it to secure all URLs now, so we should be good to go :+1:
