### ISSUE TITLE
eliminate e-mail addresses on web site

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#277]
I just received an email from our IT department and they recently went through a cyber security audit. It was suggested that we remove all references to e-mail addresses (we have been getting an outrageous amount of spam) and instead implement a contact form to send a message to an employee instead of a user seeing the employee e-mail.

An example they gave me was for the [Monroe ISD](https://www.monroeisd.us/about/contactinfo/empdirectory/). If you click on the name of a person, and then click on "send me a message" a pop up form shows up where someone could email an employee and then that message would send directly to that employee. If we implement something like this it would allow us to eliminate references to e-mail addresses. 

As another layer, we would have to make sure that the pop up is accessible ( I haven't really read up on pop ups and how they affect screen readers) but I was thinking maybe we could make the form fly in from the left? 

I'm sure this project is a lot more involved than just creating a new form. If you could let me know the scope of this project and any other thoughts/ideas you have that would be great!

**Comment by d4mation** [comment]
Are email addresses only shown on Employee Pages currently, or are they also shown on other, more general, pages? Such as "Email so-and-so for more information" and things like that on something like a Program Page?

**Comment by d4mation** [comment]
Also, are there any instances where more than one such email address is displayed on the page?

**Comment by banksashleym** [comment]
Yes, we have e-mail addresses on both the employee pages and also on general pages as well. And yes, there are pages that do have more than one e-mail address on the same page.

**Comment by banksashleym** [comment]
Hello! I noticed that when I click on someone's email address that a form now pops in and you can now e-mail using the form?? This is great! I just wanted to double check that that was from this job and not something I may have inadvertently done lol...If so i will move forward with letting employees know they will be receiving emails in this sort of format for those that are contacting them from the website. Thanks!

**Comment by banksashleym** [comment]
Nevermind! It seems as though that same digital advertising company who created the proxied site for us provided a pixel to track our campaign and that was what was creating the form. I have removed that I am going to have a conversation with Dotty about not placing any sort of tracking pixels out there anymore.

**Comment by d4mation** [comment]
@banksashleym I am planning on working on this feature today. I've got a plan in place for handling the Staff listings, as well as anywhere that the `[email]` shortcode is used. But there are two clarifying questions that I have for other instances:

1. Jobs for Jets pages have email addresses as well looking at the theme template files for the Jobs for Jets archive. However, the archive is not enabled for that Content Type and the Content Type itself does not appear to be in use any longer. Should this be implemented here as well? Looking at how it was used, these were not necessarily JC emails so maybe their exposure isn't as important?

2. Are there any cases where email addresses are being included directly within the WYSIWYG Editor? These will require manual intervention for each occurrence. The process will work similarly to the solution I'm implementing for Staff listings and the `[email]` shortcode, but it will be a separate shortcode that will have to be used.

**Comment by banksashleym** [comment]
Hi Eric, thanks!
1. Jobs for Jets has actually been decommissioned and the plugin isn't active anymore. You can disregard any integration for Jobs for Jets
2. Yes, actually all of the e-mail addresses on pages/posts are manually entered :) I figured I would have to do a search and manually replace with the shortcode and that's ok.

**Comment by d4mation** [comment]
@banksashleym 

I have implemented this on the Staging site. For Staff and the already existing `[email]` shortcode, this will work automatically with no action on your part. 

For emails that live within the WYSIWYG Content in Posts/Pages, a new shortcode called `[generic_email]` has been added.

In order to use it, you have to fill out these fields at the bottom of the Edit screen. This is where you can identify and store Email Addresses to use on the page without exposing them to visitors on the website. 

By giving it a unique identifier, you can include a shortcode like the following to have a Form that will send to that Email Address added using a pop-over anywhere on the page:

```
[generic_email id="test"]
Link Text
[/generic_email]
```

You can also pass through `post_id` parameter if you want to pull data from a different Post/Page. That will likely not be a common use-case, but I wanted to point it out.

Here's an example of how I configured it for testing: 

![image](https://user-images.githubusercontent.com/7770631/52373164-060bb600-2a28-11e9-9d45-c3f3d781a702.png)

![image](https://user-images.githubusercontent.com/7770631/52373000-98f82080-2a27-11e9-9f98-cce4413760ff.png)

Let me know if you have any questions are anything needs to be changed! If this is all good, we'll get this up and live 👍

**Comment by banksashleym** [comment]
Good morning! Eric, this is amazing and absolutely what we were envisioning. Could you style the email addresses in the staff emails so that email reads "E-mail" we have to follow a style guide here and that's the way we determined that we would write email :) 

Also, when I did the test submissions both emails came to my junk folder. Is there any specific info that I could tell our IT department to get all of the web emails whitelisted so that they come straight to our employees inbox? 

This is great, thank you so much!!

**Comment by d4mation** [comment]
Went ahead and fixed the "E-mail" hyphenation 👍 

> Also, when I did the test submissions both emails came to my junk folder. Is there any specific info that I could tell our IT department to get all of the web emails whitelisted so that they come straight to our employees inbox?

This is likely caused by something within your email system. When an email is sent by any of the forms that handle this currently, they are being sent by the Admin Email on the site (BanksAshleyM@jccmi.edu) _but_ it is technically being sent on behalf of your email address via mail.wpengine.com.

Here's a screenshot of the Email Header for a test email I just sent myself. Despite showing my name and the fact that replying to it would go to my email address, it was sent using yours via WP Engine's server.

![image](https://user-images.githubusercontent.com/7770631/52426635-4f154600-2acc-11e9-997f-d4b0e17d13af.png)

Your mail servers may consider this a spoofing attempt and are spamming it as a result. 

I cannot really tell you exactly how this needs to be addressed as it would be different depending on what service you use for email at JC. But if you use Exchange, it is possible that it could be due a "Block External Spoofing" being set. Another client of ours who has had this issue in the past while using Exchange created a separate "no-reply@" email address and whitelisted that one from that rule and set it up to be used for any emails going out from the website.

**Comment by banksashleym** [comment]
Thanks Eric! I ran this by our IT department and they just had a few suggestions:

- Can we have the email come from a different e-mail than my e-mail address? Our IT can create a separate email address, maybe something along the lines of web-form-inquiry@jccmi.edu - or maybe this is where we can add the no-reply@ email? 

- For the e-mail that goes to the inbox, could we call it **New Submission from Website Contact Form**?

- Could we eliminate the Staff ID field that shows up in the e-mail to the employee?

They are also still trying to figure out how to whitelist these e-mails. They added mail.wpengine.com and they still seem to be going to the junk folder, so i will keep you posted when they get that figured out.

Thank you!

**Comment by d4mation** [comment]
Another thing to try would be to alter the SPF field in the DNS. 

https://wpengine.com/support/dmarc-best-practices-get-email-inbox/

> Can we have the email come from a different e-mail than my e-mail address?

Yes, we can make it go anywhere :+1:

> For the e-mail that goes to the inbox, could we call it **New Submission from Website Contact Form**?

Yes, we can change that to whatever you'd like. Should that be for all three types of Forms? (Staff emails, the Company Email via `[email]`, and the generic email form `[generic_email]`) Or should it be something different for each? 

> Could we eliminate the Staff ID field that shows up in the e-mail to the employee?

I'll see if I can get those cleanly removed from the resulting email. The `[generic_email]` form would send both the Email ID and the Post ID as well which I can see as being potentially confusing to the recipient.

**Comment by banksashleym** [comment]
Perfect! I just spoke with IT and they were able to whitelist the e-mails and they are now coming in our inboxes. 
-If we could have the subject line read: **New submission from Jackson College contact form** I think that covers all bases
-That would be great if we could have the email ID/Post ID removed.

Thanks!

**Comment by d4mation** [comment]
> Sorry one more thing: I'm assuming the email address the email comes from has to be a valid e-mail? If so I will have IT create the " [web-form-inquiry@jccmi.edu](mailto:web-form-inquiry@jccmi.edu)"

_Technically_ no. But it could be possible that on your end, your email servers may recognize that it is fake and spam it for that reason. We could try it with a fake email address first if you'd like? 

Also, could you let me know exactly what IT did to fix this problem, please? That way we can add this to our own knowledge base. 👍

**Comment by banksashleym** [comment]
Of course! Here is the response from IT:

> I created an exchange transport rule based on the IP address range they are sending from and had it set the spam confidence and append content to the header which makes it bypass the clutter folder. See the screenshot for details.
![pic](https://user-images.githubusercontent.com/15264315/52494659-8e12cc80-2b9c-11e9-967d-ea1507f510fd.jpg)

**Comment by banksashleym** [comment]
Hi Eric, could we go ahead and make these e-mails come from web-form-inquiry@jccmi.edu instead of banksashleym@jccmi.edu? IT is supposed to be creating this email address but i will test it to see if it's going to the junk folder. Thanks!

**Comment by d4mation** [comment]
I have just updated the 3 forms used by this system to send From that email address on Staging :+1:

**Comment by banksashleym** [comment]
Perfect! These are coming to my inbox so i think we are good to make this live! Woo!

**Comment by BigActual** [comment]
@d4mation is this OK to close?

**Comment by d4mation** [comment]
Not yet. I still need to push this live.

**Comment by d4mation** [comment]
This change is now Live :+1:

The Staff and `[email]` shortcodes will work automatically, but any emails that are in the Post Content will need to be replaced with the `[generic_email]` shortcode.

**Comment by banksashleym** [comment]
Thank you!!

**Comment by banksashleym** [comment]
Is there a way to clear the cache on these forms? For instance, when I send myself a test email in the employee directory and then go to email someone else, the confirmation pops up instead of a new form...when I refresh the page I'm able to see the form again. It's not a big deal since I doubt someone is going to e-mail more than one person per page, but you never know :)

**Comment by d4mation** [comment]
The best way to accomplish that would be to have a separate Form Pop-Up for every Staff Member. Right now they are being re-used.

If you want to open another Issue for that I could rig that up on Staging to ensure nothing funky happens :+1:

**Comment by banksashleym** [comment]
Ok, I will ask around and see if that a big enough deal to warrant doing another issue! I would assume most people would know to refresh the page...but then again I've gotten in trouble with assuming!

Also, sorry just one more thing. I'm going through and adding the shortcode and it seems to be putting a space after the shortcode? See the [Foundation page](https://www.jccmi.edu/foundation/foundation-scholarships/).
