### ISSUE TITLE
SSL certificate on subsites

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#278]
Hello, is it possible to make our SSL certificate active on all of our subsites? Or will we need to have a separate certificate for each subsite? Thanks!

**Comment by BigActual** [comment]
It's separate for each one. @d4mation would you please activate these for Ashley during the next sprint, on Wed.?

**Comment by d4mation** [comment]
Well, this is where it can get confusing. JC isn't using the built-in Let's Encrypt SSL Certs that are provided by WP Engine but are rather providing their own.

With the one that they have currently, it may be possible to get a Wild Card Cert, but then it would be a matter of finding out how to make that work with WP Engine (The one in use now had to be provided to and installed by the WP Engine techs).

Using separate, free, Let's Encrypt Certs for each sub-site would be the easier route. But it may not be the only route in their case. I'm not sure if there'd be any major benefit to using a Wild Card except for the ability to create new Sub Sites without going through the process to get them their own Cert though.

**Comment by BigActual** [comment]
@banksashleym is there a reason to stay with your current provider at all when there is a free Let's Encrypt certificate available through WP Engine?

**Comment by banksashleym** [comment]
I will ask IT about that. They have always been the department to do our SSL certificate. I'm not sure they know that there is a free option. I will run it by them and see what they say. Thanks!

**Comment by BigActual** [comment]
Curious, @banksashleym , how did it go?

**Comment by banksashleym** [comment]
I haven't heard back from IT yet about this issue - but I will send a reminder email...thanks!!

**Comment by banksashleym** [comment]
Heard back from IT about the SSL certificates and this is the response: 
----------
Tim and Randy would like to continue to use SSL certificates generated by COMODO versus Let’s Encrypt SSL. 

One thought they had was to use a wildcard certificate that was limited to just your subsites versus all of jccmi.edu. In order to do that though we’d need to make the subsites have a consistent naming convention. 

For example: 

hccap.X.jccmi.edu
hcemc.X.jccmi.edu
jclisd.X.jccmi.edu
events.X.jccmi.edu
assessment.X.jccmi.edu
intranet.X.jccmi.edu

Where X could me whatever you decided to name it; like intranet.www2.jccmi.edu or intranet.sub.jccmi.edu. Then we could purchase a wildcard certificate that was tied to *.X.jccmi.edu and you could add as many subsites as you wanted as long as they were in the same format. If you wanted to make the URLs easier to access I would suggest just creating redirects off of www.jccmi.edu like www.jccmi.edu/intranet that points to intranet.x.jccmi.edu.
----------
Let me know your thoughts on this! Will I be able to go into WP Engine and change the url to this type of format or will the sites have to be added from scratch? Thanks!

**Comment by banksashleym** [comment]
Just checking to see if this is going to screw up any existing projects if I tell our IT to use the above formula to implement a wildcard certificate? I would love to have them implement these ssl certificates this week. I was thinking of using:

intranet.1.jccmi.edu, hcemc.1.jccmi.edu, etc for all subsites...Let me know if you think this will be a problem or if you're good with it?

Thanks!!

**Comment by BigActual** [comment]
@banksashleym , would you please call me on this. It will require coordinating our schedules.

**Comment by BigActual** [comment]
@banksashleym , Thanks for the phone call. I spoke with @d4mation and he will update this issue shortly. The gist of it is; your formatting is likely fine. He will go into the details with you.

Steve

**Comment by d4mation** [comment]
There should be no issue with the formatting. The subsites do not need to be an immediate sub-domain of the primary domain for them to function. In fact, we have a subsite on one of our own multisites that is its own domain entirely. 

There are a few steps that will need to be taken care of:

1. We will need to add the Domains to the WP Engine account under https://my.wpengine.com/installs/jacksoncollege/domains
  - We will just need a complete list of all the new domains with their formatting to know what to add
2. We will need to do a Search/Replace on the database to replace the old domains with the new domains
3. The new domains will need to be pointed at the WP Engine server by editing the DNS Zone File
4. The new SSL Cert will need to be uploaded here https://my.wpengine.com/installs/jacksoncollege/ssl_certificates/add

1 and 2 we can take care of, but it seems that 3 and 4 may need to be handled by your IT Team. 

We will want to coordinate these efforts as best as we can because after I do 1 and 2, the sites will be inaccessible until at least 3 is complete. Without 4, it could show errors about SSL not being available for those sites.

**Comment by banksashleym** [comment]
Thanks! I have forwarded this on to IT. I talked to Steve about possibly completing this next Wednesday if that works for you? If you let me know when you complete steps 1 and 2 I will let IT know that on Wednesday they can do 3 and 4. 

For right now if we could have the following added that would be great:
hcemc.1.jccmi.edu (i already added this one yesterday, but feel free to delete/re-add if I didn't do i right)
hccap.1.jccmi.edu
intranet.1.jccmi.edu

Thanks!

**Comment by BigActual** [comment]
Hi @banksashleym . Spoke with @d4mation on this. He's all set. Wednesday he'll reach out to you when he's finished with 1 and 2. Thanks.

**Comment by banksashleym** [comment]
Great, thank you!

**Comment by d4mation** [comment]
@banksashleym 

I've completed step 1. Let me know when you'd like me to begin step 2 as it will temporarily take down all the sub-sites and require a period of time where no changes are being made on the site.

**Comment by banksashleym** [comment]
Sounds good! I will forward this to IT. We really don't have any subsites active yet anyway so it's ok if the subsites are down, but to clarify doing step 2 will not let me make changes to the main site until steps 3 is completed? I will send any info to IT. Thanks!

**Comment by d4mation** [comment]
You will only be unable to make changes to the site while I'm working on 2. But I'll let you know when 2 is complete and it shouldn't take long to do.

Let me know when would be a good time to do so :+1:

**Comment by banksashleym** [comment]
Perfect, you can go ahead and complete step 2.

**Comment by d4mation** [comment]
It may take a little longer than anticipated as the database file is very large, but I'll still be sure to let you know as soon as it is complete :+1:

**Comment by banksashleym** [comment]
Sounds good, thank you!

**Comment by banksashleym** [comment]
Sorry, just to clarify again - it's not going to take the site down is it? I just won't be able to make changes?

**Comment by d4mation** [comment]
It is still up right now. It will go down incredibly briefly as I swap out the database, but that's the final step and should hopefully be the quickest. Due to the size of the database though, I need to find a different avenue of doing so than how I normally do it. There are two other ways of handling it that I know of, so I just have to decide which will work best :+1:

**Comment by banksashleym** [comment]
Perfect, thanks!

**Comment by d4mation** [comment]
I am still working on this. Both methods that I was going to try did not work in the case of your website, but I was pointed to another 3rd method which appears to be working. It is a little slower than the other two methods, but it has the benefit of the site not having to go down at all during its operation.

I'll be sure to update you once the process is complete.

**Comment by banksashleym** [comment]
Great, thank you!!

**Comment by d4mation** [comment]
Step 2 is now complete :+1: Steps 3 and 4 can begin whenever you all are ready.

**Comment by banksashleym** [comment]
Great! I will let our IT department know. I appreciate all of your help with this!

**Comment by evanjfarmer** [comment]
Hello @banksashleym, I'm new to the RBM team and am just checking in to find out the status of these JC sub-sites. I was running some updates on the main site today, and didn't want to update the rest of the Network sites until I knew that the domains were all set.

**Comment by banksashleym** [comment]
Hi Evan! These SSL sites are up and running so i think this issue can be closed. Thanks for checking!

**Comment by BigActual** [comment]
@d4mation - OK to close?
