### ISSUE TITLE
Link to a specific tab

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#280]
Hello! Is there a way to create a link to a page that incorporates the tabs shortcode and have it open directly to that tab? There is a link from the [Student Life clubs and activities](https://www.jccmi.edu/student-life/activities-clubs/) that directs the user to the [Student government](https://www.jccmi.edu/student-life/student-government/#jc-tabs-1-tab-4) page and there is a specific tab on how to form an organization. I tried to make the link go directly to that tab by adding #jc-tabs-1-tab-4 to the link but nothing happened :)

Thanks!

**Comment by d4mation** [comment]
I've just pushed this change to Staging :+1: 

I applied it to the Tabs shortcode in both the main Theme as well as the Base Theme for the subsites. 

Let me know if it is working on your end and we can get this Live.

**Comment by banksashleym** [comment]
This is perfect, thank you!

**Comment by d4mation** [comment]
I've pushed this change for both Themes to Live. 👍 You're all set!

**Comment by banksashleym** [comment]
Thank you so much!
