### ISSUE TITLE
[generic_email] and [email] shortcodes cause weird line breaks

### ISSUE THREAD

**Issue by d4mation** [JacksonCollege/jc-theme-2015#282]
Discovered in https://github.com/JacksonCollege/jc-theme-2015/issues/277#issuecomment-465640890 by @banksashleym 

This is caused by Chrome (and possibly other browsers) trying to be smart and closing out the `<p>` tag once it sees the `<div>` which contains our Pop-Over for the Form. Chrome doesn't realize though that the `<div>` gets immediately moved to the footer of the page and was never normally visible to begin with to justify closing the `<p>` tag.

This happens in-browser rather than on the server, so we need to find a clever workaround for this.

**Comment by d4mation** [comment]
@banksashleym Can you give this a once over on Staging? It seems that I was able to come up with a solution. 

https://jacksoncollege.staging.wpengine.com/foundation/foundation-scholarships/

**Comment by banksashleym** [comment]
Looks good to me, thank you so much!

**Comment by d4mation** [comment]
This change is now live 👍
