### ISSUE TITLE
Move Gravity Flow tools from the Staging Intranet to the Live Intranet

### ISSUE THREAD

**Issue by BigActual** [JacksonCollege/jc-theme-2015#284]
Licensing will likely need to be reset.

**Comment by d4mation** [comment]
I've imported the Gravity Forms and the Workflow steps to the Live site. 

Do you mean Licensing for Gravity Forms itself? I copied the License Key from Staging and it tells me it is Invalid/Expired on Live. 

I tried to remove it from Staging and then reactivate it on live in case it was an issue with the number of sites using it and it still did not work. Then when I went to activate it on Staging again it told me that it was Invalid/Expired (Before I did anything, on Staging it said it was Valid).

**Comment by BigActual** [comment]
Sorry. Gravity Flow not Gravity Forms. Gravity Flow installs and authorizes GF with a special key. You have that key, but it will only work through a Gravity Flow plugin install.

**Comment by d4mation** [comment]
All installed and ready to go 👍
