### ISSUE TITLE
Search page formatting on internet explorer 

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#285]
Hello, I had an employee let me know today that when he was using the search it was coming back looking weird. I pulled up chrome and searched and everything was looking just fine and I asked what browser he was using...internet explorer :) Sure enough something weird is happening on the search page:

![capture](https://user-images.githubusercontent.com/15264315/53755782-63f3b800-3e85-11e9-85a3-35b9fcc1b352.JPG)

**Comment by d4mation** [comment]
What version of Internet Explorer are they using? 

I tried Internet Explorer 11 in my Windows 10 Virtual Machine and it appears to load fine.

Have they tried a Hard Refresh? CTRL+F5.

![image](https://user-images.githubusercontent.com/7770631/53756081-3c511f80-3e86-11e9-8120-8845ea87beba.png)

**Comment by banksashleym** [comment]
So weird! I have version 11 on Windows 10 and its showing up weird..I tried a hard refresh and nothing changed.

**Comment by d4mation** [comment]
That is very odd. Both @BigActual and I cannot reproduce this. Neither myself in a Virtual Machine or on Steve's computer.

Here's a screencast of the page loading properly for Steve: http://recordit.co/AoiCbWhpCn

If you right-click on the page, choose "Inspect Element", and then click "Console" does anything show there? Your screenshot to me looks like the CSS itself is not loading somehow, and I believe it would show us if that were the case (I know it does in most other Browsers)

**Comment by banksashleym** [comment]
Hmmm that is odd...I clicked on "inspect element" and there is a note that says "the attached page targets document mode 5. Some console APIs and features may not be available"

I googled this it suggested using the emulation tab - when I did this and changed the document mode to 8 or above it worked. Funny thing is, I opened up the staging site on explorer and everything worked fine. I went to the emulation tab in explorer on staging and the default is set to 11.

**Comment by d4mation** [comment]
Interesting. I wonder if the computers in your office have a Group Policy set to have IE 11 target a certain compatibility mode for the site? It would explain why neither Steve or myself hit this problem. If it were set specifically for the Live Site, it would explain why the Staging site did not give you that issue as well.

https://social.technet.microsoft.com/Forums/ie/en-US/9570a903-0737-4bc7-a7c6-82bc73b8300e/ie-11-compatibility-view-selected-document-mode-is-quot5quot?forum=ieitprocurrentver#d8663b1a-0e3d-4b24-8592-b21d56247c3a

**Comment by banksashleym** [comment]
I bet that's it, i will forward this on to them and see if they can change the policy. Thank you!

**Comment by banksashleym** [comment]
This seems to have been completed as well!
