### ISSUE TITLE
Side navigation

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#29]
Sorry about these last minute changes! It's as I'm uploading and really looking at content that I'm stumbling upon new questions.

As for the side navigation, I like how it automatically populates based on the child pages, however there are many sections where I don't necessarily need to have the child page linked, need to rearrange the order (more of in order of importance vs. alpha order) and also add additional parent/child pages from other sections...would it be possible to have a little more control of the left side nav?

Thanks!

**Comment by brashrebel** [comment]
There is already an ordering mechanism built in that we can use. It can be a little time consuming to edit that value for each page but it does work effectively.
