### ISSUE TITLE
Intranet: Employee Directory

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#290]
I have enabled the staff plugin on the staging side and have added a page "employee directory." Is there a way to import the employee directory from the main JC site to the intranet? 

If we could also style the new employee directory to list the employees in columns and include a search feature instead of the A-Z feature at the top that would be great.

**Comment by d4mation** [comment]
Hmmm, well, technically you could export the content from the JC site and import it to the Intranet. But then you'd have to maintain that information in two locations.

Maybe instead the Intranet should just pull the data directly from the JC site rather than having it "live" directly within the Intranet? Then it would always be up-to-date and then you wouldn't need to worry about one of the two sites falling out-of-sync with the other.

**Comment by banksashleym** [comment]
That would be amazing. We have talked about having the full version on the intranet with the images, but doing a simpler version for the main site (just name, title, e-mail form). Would it be possible to hide the image/phone on the main site and show them on the intranet?

**Comment by d4mation** [comment]
Yep, that'd be definitely possible! That would only require some changes to the Theme that the JC site uses, and then we'd need to create a separate Theme for the Intranet site (Which should likely get its own Repository here on GitHub). 

It could be based on https://github.com/JacksonCollege/jc-base-theme if you like working with that, but if there are going to be programmatic, visual changes like this it would require a separate Theme specifically for the Intranet.

**Comment by banksashleym** [comment]
Ok, great. If we could do a separate theme I think that might be better? On the research I've done with intranets it seems like they have a different feel than a normal website? I'm envisioning something very simple though - but something that doesn't look like a mirror copy of our current site.

**Comment by d4mation** [comment]
Closing in favor of JacksonCollege/jc-intranet-theme#15
