### ISSUE TITLE
Remove 90th Profile from home page

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#291]
Hello, I worked with Joel a while back to add a direct link from our profiles area on the home page. Now that our 90th is over, can we remove that spot?

Here is the original issue, but when I open up and edit the home page I don't see the area now where I can remove that 90th spot. 

Thanks!
[Original Issue](https://github.com/JacksonCollege/jc-theme-2015/issues/234)

**Comment by d4mation** [comment]
Just pushed a fix. Thanks for reporting this!

**Comment by banksashleym** [comment]
Awesome, thanks!
