### ISSUE TITLE
Better empty events support on home page

### ISSUE THREAD

**Issue by joelworsham** [JacksonCollege/jc-theme-2015#30]
In reality, this is probably an edge case, but it could look a little bit nicer.

**Comment by brashrebel** [comment]
In case this gets punted to later, can you articulate the problem more clearly?

**Comment by joelworsham** [comment]
I plan on tackling it later rather than sooner. Basically when there's no upcoming events, it's plain, left-justified text that looks almost accidental. I'd like it to be a little more professional and intentional.
