### ISSUE TITLE
Mega Menu no longer working after updating to WP 5.5.3

### ISSUE THREAD

**Issue by d4mation** [JacksonCollege/jc-theme-2015#308]

**Comment by d4mation** [comment]
@banksashleym 

I've pushed a change to fix this to Staging: https://jccstage.wpengine.com/ Be sure to hard-refresh (CTRL+F5 on PC, CMD+SHIFT+R on Mac)

Once I have confirmation on your end that everything is working properly again I'll get this pushed to Live :+1:

**Comment by banksashleym** [comment]
Hi Eric, this is perfect! Thanks so much!

**Comment by d4mation** [comment]
GitHub Updater is giving me a little trouble seeing the Theme update. It was similarly giving me some issues when trying to get the new Branch up on Staging. 

I'll re-close this Issue once the change is fully Live.

**Comment by d4mation** [comment]
As these things go, as soon as I say something about it, it goes right through.

This change is now Live 🚀

**Comment by banksashleym** [comment]
Of course! I so appreciate you doing this, glad to be working with you again!

Ashley

**Comment by d4mation** [comment]
Actually, I noticed an issue with this fix. I'm working on fixing it now.

**Comment by d4mation** [comment]
There we go. Now this is 100% back to normal. I double-checked all the accessibility aspects of it that we had worked on before are in working order as well.

We're glad to be working with you again as well!

**Comment by banksashleym** [comment]
Thank you so much!
