### ISSUE TITLE
1. Can't save table in tablepress plugin

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#310]
Hi Eric,
WP Engine automatically updated our wordpress core (I was hesitating on updating until we signed back on with you because I read that sites were breaking!) Anyway, I am going to start adding some issues with some glitches that started occurring after the update.

When I log into the intranet (intranet.1.jccmi.edu), I am unable to save a table in the TablePress plugin after making a change. The button "clicks" but nothing happens after that.

**Comment by d4mation** [comment]
This was fixed with JacksonCollege/jc-intranet-theme#27
