### ISSUE TITLE
5. Not able to add documents through media library on intranet and main site

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#314]
On the intranet as well as the main site, I am not able to use the media library to add documents, but it does allow me to add images.

For instance, if I'm on a page and go to "add media" I can navigate to a pdf and place it on the page. The text shows up, but there is no link attached. I have to switch to text tab and manually add in the link.

Thank you!

**Comment by d4mation** [comment]
This was fixed with JacksonCollege/jc-intranet-theme#27
