### ISSUE TITLE
Remove gray sidebar when news item is set to full width

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#318]
Hello! Is it possible to remove the gray sidebar when a news item sidebar settings are set to the full width? Example, we are having an MLK celebration and we created a news release at https://www.jccmi.edu/king-day-2021/. I selected the full width in the sidebar settings in wordpress (all the way down the page) and everything was stripped except the gray sidebar. Thanks!

**Comment by d4mation** [comment]
This seems to be related to #24

A Widget Area/Sidebar called "News" exists which is supposed to populate this area. It currently has no Widgets in it.

Would you like News Items to show as Full Width if no Widgets are set in this Widget Area? If so, do you want the gray background to completely go away? Or just to shift the main content over to the left? 

There does not appear to be any other full width templates that I can see looking at the theme files.

**Comment by banksashleym** [comment]
Normally these news items are set to have the left sidebar with the recent news and archives (I added those widgets back in - not sure how they disappeared) but is it possible if a news item is set to full width that the left side widgets and gray bar disappear and the content is then distributed the full width of the page? This is how the full width templates work for pages. Thanks!

**Comment by d4mation** [comment]
Can you link me to a page that is using a full-width template, please? When I looked through the code I didn't see any full-width templates.

**Comment by banksashleym** [comment]
Sure! There are a few pages on the site where I select the full width setting on "sidebar settings" (at the bottom of the page in wordpress when I am editing a page) and then use the [row][columns] shortcode to define columns. These full width pages are still set to "default template" in the Page Attributes: Template area. That is something I've always had on my list is to define a few more templates so that these full width pages follow some sort of template, but for now they are all just one off pages laid out with columns.

**Comment by d4mation** [comment]
Can you link me to a specific page where you've done this, please? Looking at the code in the Theme, there shouldn't be a way to have a full-width page as the Sidebar is always loaded in. 

I want to be sure I can address this correctly for you on the Blog Posts/News Posts.

**Comment by banksashleym** [comment]
Whoops! Yes, our [Health Clinic](https://www.jccmi.edu/health-clinic/) page is set so that the sidebar settings are set to full width

**Comment by d4mation** [comment]
Ah, thank you so much! I see how this was implemented now and why it wasn't working for News posts.

I've made the adjustments necessary for this. Now any News post you configure to have no Sidebar will actually have no Sidebar. This change is now Live.
