### ISSUE TITLE
Plugin Updates

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#319]
Hello! Not sure how the updates work for our site now that we have a maintenance agreement? Are the updates something that you would like me to put in a Github issue for? There are currently 19 updates.

Thanks!

**Comment by BigActual** [comment]
We run updates on Tuesdays. We'll take care of them today.

**Comment by banksashleym** [comment]
Great, thank you!

**Comment by BigActual** [comment]
Ashley, 
Some of the updates were major so I ran them on staging to ensure we didn't have any conflicts. Everything looks good to me but I’d like you to sign off. Would you please go to staging and verify that the site is working as advertised. Here are the items that could use review and approval:

Also, I turned off updates via WP Engine. We're running a program that's more effective. 

Here is a link to staging (Your login information from live will work here) - https://jccstage.wpengine.com/
​
​If you approve, let me know and I’ll apply the updates on live.

Thanks,
Steve

**Comment by banksashleym** [comment]
Good morning! I spent this morning going through the staging site and I didn't see anything out of the ordinary. You have my approval to proceed with applying the updates. And thanks for turning of the WP Engine smart plugin manager - it never really worked right and I have been meaning to do that. Thanks!

**Comment by BigActual** [comment]
Updates pushed out on live. Looks great. I'm closing this issue, but feel free to reopen it if you find any issues.
