### ISSUE TITLE
News page image position

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-theme-2015#86]
Would it be possible on a news page to have the feature image float right with the text wrapping around the left?

This doesn't have to be done before we launch, just something I wanted to note :)

Thanks!

http://jacksoncollege.staging.wpengine.com/enjoy-evening-steven-curtis-chapman-jc/?preview=true

**Comment by joelworsham** [comment]
:+1:

**Comment by banksashleym** [comment]
Closing this as it was completed.
