### ISSUE TITLE
Closing language selector

### ISSUE THREAD

**Issue by brashrebel** [JacksonCollege/jc-theme-2015#97]
On a computer, after opening the Select Language element, you can close it by clicking somewhere else on the screen but not by clicking on the Select Language link again. I think clicking it again should close it. Also, on a touch screen it can't be closed at all except by selecting a language.

**Comment by joelworsham** [comment]
This is the behavior that Google implements, as the button on the site is only a wrapper for the Google Plugin. I can look into "overriding" the behavior, but I can't make any promises.

**Comment by brashrebel** [comment]
May the force be with you!

**Comment by joelworsham** [comment]
http://www.quickmeme.com/img/3f/3fb29224aef8bf439805a28bed43a9acde8a820e00efe4f877477bbc954e725f.jpg
