### ISSUE TITLE
Library "need help" not linked somewhere

### ISSUE THREAD

**Issue by brashrebel** [JacksonCollege/jc-theme-2015#98]
On the /library/ page, the "need help" button just links to the image. I guess there could be a case where that image was helpful to someone but I'm just gonna guess here that most people won't consider their problems solved by getting that. I could be wrong though.

**Comment by banksashleym** [comment]
Awesome, thanks for catching this too..I am going to convert these over to the interactive buttons. This was just a workaround when I was pasting our content over and I must have forgotten to link the image to the need help page.

Thanks!
