### ISSUE TITLE
Library page action items not consistent with theme

### ISSUE THREAD

**Issue by brashrebel** [JacksonCollege/jc-theme-2015#99]
Not necessarily a big problem, but the images used for linking to relevant content on the [library page](http://www.jccmi.edu/library/) strike me as a break in the site's consistent theme. I recommend revising this to be more inline with the rest of the site. An example of a layout that could be used would be the [academics](http://www.jccmi.edu/academics/) page with the square images that link somewhere or the [programs of study](http://www.jccmi.edu/academics/programs-of-study/) page or even just buttons similar to what is in the left sidebar for requesting info and a campus visit.

**Comment by banksashleym** [comment]
Exactly, this was just a workaround before our button shortcodes/content grids were created. I have this on my list to update before we launch! Thanks for catching this!
